### PR TITLE
[4.0] Installer review

### LINKED ISSUE #15583: [4.0] Installer doesnt validate that the mysql database name is valid
At the moment there is no validation, if you enter an invalid mysql database name (like 'joomla-4') then the installation doesnt warn, but hangs on a later step (creating the db) 

screen shot 2017-04-26 at 13 18 49

### LINKED ISSUE #21359: [4.0] Installation Screen Link to Joomla disappears on hover
### Steps to reproduce the issue
When installing a new Site, hover the links in the right bottom corner of the installation screen. The Link colour is already dark, at hover is is darkened again and links become invisible.

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes lots of small things - shouldn't really be in a single PR but otherwise it would be merge conflict hell

- [a11y] Joomla logo is a decorative image only so should not have an alt description
- Remove duplicate system-message-container div - important so we have unique id
- fontawesome is include in the template.css by the sccs - no need to load it again
- update code comment it is super user not super admin etc
- use quote and quotename not q and qn
- namespace - JText
- Namespace JHtml
- [a11y] Help Docs link - add a link to the docs site and meaningful text for screenreaders to the "lightbulb"
- [a11y] Add h1 to the page
- [a11y] change section role=main to just < main >
- You can not use a custom element to display the noscript message - obviously that's not going to work because the custom element is javascript - inception
- [a11y] Move message about installing languages to be a caption 
- [a11y] add scope to languages table
- [a11y] contrast on language version number
- [a11y] Section headings not nested correctly h1->h3 now h1->h2
- Namespace JFile
- Namespace Jfolder
- target blank on mysql8 link to docs
- [a11y] footer link color and hover fixes #21359
- Validate name of database fixes #15583
- remove all references to switcher - not being used and it breaks scss compile
- template.css after running npm build:css [note this hadn't been run for a while as it was missing from the build scripts] #21446

### CODE REVIEW

File: installation/src/Model/LanguagesModel.php [hunk 1]
```diff
@@ -96,11 +97,11 @@ public function getItems()
 		$db        = Factory::getDbo();
 		$extQuery  = $db->getQuery(true);
 
-		$extQuery->select($db->qn('extension_id'))
-			->from($db->qn('#__extensions'))
-			->where($db->qn('type') . ' = ' . $db->q('package'))
-			->where($db->qn('element') . ' = ' . $db->q('pkg_en-GB'))
-			->where($db->qn('client_id') . ' = 0');
+		$extQuery->select($db->quotename('extension_id'))
```
Comment (wilsonge) [inline installation/src/Model/LanguagesModel.php]: `quoteName` :/

File: installation/src/Form/Field/Installation/SampleField.php [hunk 2]
```diff
@@ -51,21 +55,21 @@ protected function getOptions()
...
 		// Build the options list from the list of files.
 		if (is_array($files))
 		{
 			foreach ($files as $file)
 			{
-				$options[] = \JHtml::_('select.option', $file, Factory::getLanguage()->hasKey($key = 'INSTL_' . ($file = \JFile::stripExt($file)) . '_SET') ?
-					\JHtml::_('tooltip', \JText::_('INSTL_' . strtoupper($file = \JFile::stripExt($file)) . '_SET_DESC'), '', '',
-						\JText::_('JYES')
+				$options[] = HTMLHelper::_('select.option', $file, Factory::getLanguage()->hasKey($key = 'INSTL_' . ($file = File::stripExt($file)) . '_SET') ?
+					HTMLHelper::_('tooltip', Text::_('INSTL_' . strtoupper($file = File::stripExt($file)) . '_SET_DESC'), '', '',
```
Comment (dgrammatiko) [inline installation/src/Form/Field/Installation/SampleField.php:71]: There are no tooltips in the installation, neither I think there will ever be a need for tooltips if everything is self-explanatory

Comment (wilsonge) [reply installation/src/Form/Field/Installation/SampleField.php:71]: This will naturally go away once we remove the sample data field. I think it's outside the scope of this PR to change this though - it's currently there - all Brians done is namespace the call

Comment (brianteeman) [reply installation/src/Form/Field/Installation/SampleField.php:71]: i was just fixing the namespacing here

**Comment by wilsonge** [comment]
@puneet0191  @rdeutz the change here to change the header level is breaking system tests - can you guys help @brianteeman with fixing the tests please

**Comment by brianteeman** [comment]
i did look in the system tests repo but couldnt see this test that is failing

**Comment by brianteeman** [comment]
@wilsonge the failing system test has been failing before this PR as well - for example
http://ci.joomla.org/joomla/joomla-cms/8186/15

**Comment by wilsonge** [comment]
For sure that's been a problem before. But given you've removed the h3 it searches for (I think) it's going to fail 100% of the time now rather than like 70% of the time

**Comment by puneet0191** [comment]
@brianteeman check for the function here: https://github.com/joomla-projects/joomla-browser/blob/v4.0.0/src/JoomlaBrowser.php 
Installation and some other generic functions are part of Joomla Browser, you can search the function being called for installation on that file.

**Comment by brianteeman** [comment]
@wilsonge @puneet0191 done see https://github.com/joomla-projects/joomla-browser/pull/179

**Comment by rdeutz** [comment]
please ping me when this one is ready to merge, I will take care of the right merge order

**Comment by brianteeman** [comment]
~Don;t merge anything yet - the database name validation regex isnt working~

**Comment by brianteeman** [comment]
~I have no idea why this isn't working
`		if (isset($options->db_name) && !preg_match('^[a-zA-Z_][0-9a-zA-Z_\$]*', $options->db_name))
`~

File: installation/tmpl/remove/default.php [hunk 3]
```diff
@@ -79,64 +82,64 @@
...
 
 		<fieldset id="installLanguages" class="j-install-step">
 			<legend class="j-install-step-header">
-				<span class="fa fa-commenting-o" aria-hidden="true"></span> <?php echo JText::_('INSTL_LANGUAGES'); ?>
+				<span class="fa fa-commenting-o" aria-hidden="true"></span> <?php echo Text::_('INSTL_LANGUAGES'); ?>
 			</legend>
 			<div class="j-install-step-form">
 				<?php if (!$this->items) : ?>
-				<p><?php echo JText::_('INSTL_LANGUAGES_WARNING_NO_INTERNET') ?></p>
+				<p><?php echo Text::_('INSTL_LANGUAGES_WARNING_NO_INTERNET') ?></p>
```
Comment (Quy) [inline installation/tmpl/remove/default.php]: Add semicolon

File: installation/tmpl/remove/default.php [hunk 4]
```diff
@@ -79,64 +82,64 @@
...
 					<a href="#"
 							class="btn btn-primary"
 							onclick="return Install.goToPage('remove');">
 						<span class="fa fa-arrow-left icon-white"></span>
-						<?php echo JText::_('INSTL_LANGUAGES_WARNING_BACK_BUTTON'); ?>
+						<?php echo Text::_('INSTL_LANGUAGES_WARNING_BACK_BUTTON'); ?>
 					</a>
 				</p>
-				<p><?php echo JText::_('INSTL_LANGUAGES_WARNING_NO_INTERNET2') ?></p>
+				<p><?php echo Text::_('INSTL_LANGUAGES_WARNING_NO_INTERNET2') ?></p>
```
Comment (Quy) [inline installation/tmpl/remove/default.php]: Add semicolon

File: installation/tmpl/remove/default.php [hunk 5]
```diff
@@ -79,64 +82,64 @@
...
 			<?php else : ?>
 			<form action="index.php" method="post" id="languagesForm" class="form-validate">
-				<p id="install_languages_desc"><?php echo JText::_('INSTL_LANGUAGES_DESC'); ?></p>
 				<p id="wait_installing" style="display: none;">
-					<?php echo JText::_('INSTL_LANGUAGES_MESSAGE_PLEASE_WAIT') ?><br>
+					<?php echo Text::_('INSTL_LANGUAGES_MESSAGE_PLEASE_WAIT') ?><br>
```
Comment (Quy) [inline installation/tmpl/remove/default.php]: Add semicolon

File: installation/tmpl/remove/default.php [hunk 6]
```diff
@@ -79,64 +82,64 @@
...
-					<!-- <input type="button" class="btn btn-warning" name="instDefault" onclick="Install.removeFolder(this);" value="<?php echo JText::_('INSTL_COMPLETE_REMOVE_FOLDER'); ?>"> -->
+					<!-- <input type="button" class="btn btn-warning" name="instDefault" onclick="Install.removeFolder(this);" value="<?php echo Text::_('INSTL_COMPLETE_REMOVE_FOLDER'); ?>"> -->
 				<?php endif; ?>
-				<?php echo JHtml::_('form.token'); ?>
+				<?php echo HTMLHelper::_('form.token'); ?>
 
 				<div class="form-group">
-					<a class="btn btn-primary btn-block" href="<?php echo JUri::root(); ?>" title="<?php echo JText::_('JSITE'); ?>"><span class="fa fa-eye"></span> <?php echo JText::_('INSTL_COMPLETE_SITE_BTN'); ?></a>
-					<a class="btn btn-primary btn-block" href="<?php echo JUri::root(); ?>administrator/" title="<?php echo JText::_('JADMINISTRATOR'); ?>"><span class="fa fa-lock"></span> <?php echo JText::_('INSTL_COMPLETE_ADMIN_BTN'); ?></a>
+					<a class="btn btn-primary btn-block" href="<?php echo JUri::root(); ?>" title="<?php echo Text::_('JSITE'); ?>"><span class="fa fa-eye"></span> <?php echo Text::_('INSTL_COMPLETE_SITE_BTN'); ?></a>
```
Comment (Quy) [inline installation/tmpl/remove/default.php]: Add `aria-hidden="true"` and also next line.

File: installation/tmpl/remove/default.php [hunk 7]
```diff
@@ -79,64 +82,64 @@
...
 						<div class="form-check">
 							<label class="form-check-label">
 								<input type="checkbox" class="form-check-input">
-								<?php echo JText::_('INSTL_SITE_DEVMODE_DESC'); ?>
+								<?php echo Text::_('INSTL_SITE_DEVMODE_DESC'); ?>
 							</label>
 						</div>
 					</div>
-					<!-- <input type="button" class="btn btn-warning" name="instDefault" onclick="Install.removeFolder(this);" value="<?php echo JText::_('INSTL_COMPLETE_REMOVE_FOLDER'); ?>"> -->
+					<!-- <input type="button" class="btn btn-warning" name="instDefault" onclick="Install.removeFolder(this);" value="<?php echo Text::_('INSTL_COMPLETE_REMOVE_FOLDER'); ?>"> -->
```
Comment (Quy) [inline installation/tmpl/remove/default.php:95]: Remove comment?

File: installation/tmpl/preinstall/default.php [hunk 8]
```diff
@@ -38,27 +41,27 @@
 				<?php if ($option->state === false && preg_match('$configuration.php$', $option->label)) : ?>
 					<div id="ftpOptions" class="ftp-options mb-4 hidden">
 						<form action="index.php" method="post" id="ftpForm" class="form-validate">
-							<!-- 					<h3><?php echo JText::_('INSTL_FTP'); ?></h3>
+							<!-- 					<h3><?php echo Text::_('INSTL_FTP'); ?></h3>
```
Comment (Quy) [inline installation/tmpl/preinstall/default.php:44]: Remove comment?

File: installation/src/Model/LanguagesModel.php [hunk 9]
```diff
@@ -1112,12 +1113,12 @@ public function disableModuleMainMenu()
...
-			->set($db->qn('published') . ' = 0')
-			->where($db->qn('module') . ' = ' . $db->q('mod_menu'))
-			->where($db->qn('language') . ' = ' . $db->q('*'))
-			->where($db->qn('client_id') . ' = ' . $db->q('0'))
-			->where($db->qn('position') . ' = ' . $db->q('sidebar-right'));
+			->update($db->quoteName('#__modules'))
+			->set($db->quoteName('published') . ' = 0')
+			->where($db->quoteName('module') . ' = ' . $db->quote('mod_menu'))
+			->where($db->quoteName('language') . ' = ' . $db->quote('*'))
+			->where($db->quoteName('client_id') . ' = ' . $db->quote('0'))
```
Comment (Quy) [inline installation/src/Model/LanguagesModel.php]: Change to `->where($db->quoteName('client_id') . ' = 0')`

File: installation/src/Model/DatabaseModel.php [hunk 10]
```diff
@@ -205,7 +216,7 @@ public function initialise()
 			// When all checks have been passed we don't need to do this here again.
 			if ($remoteDbFileTestsPassed === false)
 			{
-				$generalRemoteDatabaseMessage = \JText::sprintf(
+				$generalRemoteDatabaseMessage = Text::sprintf(
```
Comment (Quy) [inline installation/src/Model/DatabaseModel.php:219]: Something is up in this area. See screenshot.

File: installation/template/error.php [hunk 11]
```diff
@@ -39,38 +41,35 @@
...
 				<div class="container-installation flex">
 					<div class="j-install-step active">
 						<div class="j-install-step-header">
-							<span class="fa fa-exclamation" aria-hidden="true"></span> <?php echo JText::_('INSTL_ERROR'); ?>
+							<span class="fa fa-exclamation" aria-hidden="true"></span> <?php echo Text::_('INSTL_ERROR'); ?>
 						</div>
 						<div class="j-install-step-form">
 							<div class="alert preinstall-alert">
 								<div class="alert-icon">
 									<span class="alert-icon fa fa-exclamation-triangle"></span>
```
Comment (Quy) [inline installation/template/error.php]: Add ` aria-hidden="true"`

File: installation/tmpl/remove/default.php [hunk 12]
```diff
@@ -79,64 +82,64 @@
...
-				<span class="fa fa-commenting-o" aria-hidden="true"></span> <?php echo JText::_('INSTL_LANGUAGES'); ?>
+				<span class="fa fa-commenting-o" aria-hidden="true"></span> <?php echo Text::_('INSTL_LANGUAGES'); ?>
 			</legend>
 			<div class="j-install-step-form">
 				<?php if (!$this->items) : ?>
-				<p><?php echo JText::_('INSTL_LANGUAGES_WARNING_NO_INTERNET') ?></p>
+				<p><?php echo Text::_('INSTL_LANGUAGES_WARNING_NO_INTERNET') ?></p>
 				<p>
 					<a href="#"
 							class="btn btn-primary"
```
Comment (Quy) [inline installation/tmpl/remove/default.php]: Fix indentation.

File: installation/tmpl/remove/default.php [hunk 13]
```diff
@@ -79,64 +82,64 @@
...
 							onclick="return Install.goToPage('remove');">
 						<span class="fa fa-arrow-left icon-white"></span>
```
Comment (Quy) [inline installation/tmpl/remove/default.php]: Add ` aria-hidden="true"`

File: installation/src/Model/DatabaseModel.php [hunk 14]
```diff
@@ -131,47 +134,55 @@ public function initialise()
...
 		if (strlen($options->db_name) > 64)
 		{
-			Factory::getApplication()->enqueueMessage(\JText::_('INSTL_DATABASE_NAME_TOO_LONG'), 'warning');
+			Factory::getApplication()->enqueueMessage(Text::_('INSTL_DATABASE_NAME_TOO_LONG'), 'warning');
+
+			return false;
+		}
+
+		// Validate database name.
+		if (isset($options->db_name) && !preg_match('^[a-zA-Z_][0-9a-zA-Z_\$]*', $options->db_name))
```
Comment (ggppdk) [inline installation/src/Model/DatabaseModel.php]: please,
add start and end character  e.g. /  or #
no need to escape $ inside character class []
you want to compare (match) to the full text of $options->db_name so add $ at the end of the expression
no need for `isset($options->db_name) &&` it was checked if it was empty in above code
```php
if (!preg_match('/^[a-zA-Z_][0-9a-zA-Z_$]*$/', $options->db_name))
```

File: installation/src/Model/DatabaseModel.php (hunk 10 above)
Comment (wilsonge) [reply installation/src/Model/DatabaseModel.php:219]: That’s fine. GitHub doesn’t like the way the lines are commented out. These need to be uncommented before stable (https://github.com/joomla/joomla-cms/issues/18736)

File: installation/src/Model/DatabaseModel.php (hunk 14 above)
Comment (brianteeman) [reply installation/src/Model/DatabaseModel.php]: thanks I will check

File: installation/tmpl/preinstall/default.php (hunk 8 above)
Comment (brianteeman) [reply installation/tmpl/preinstall/default.php:44]: no not yet as the ftp stuff hasnt been checked to see if it is 
- working
- required

we havent been able to setup/find a server for testing

File: installation/tmpl/remove/default.php (hunk 7 above)
Comment (brianteeman) [reply installation/tmpl/remove/default.php:95]: intentional for now. we have a release blocker issue created as a reminder

File: installation/tmpl/remove/default.php (hunk 3 above)
Comment (brianteeman) [reply installation/tmpl/remove/default.php]: Thanks

as this is a bug in the original code I will do a bigger scan to see if there are others

File: installation/src/Model/DatabaseModel.php (hunk 14 above)
Comment (brianteeman) [reply installation/src/Model/DatabaseModel.php]: thanks - that worked

**Comment by brianteeman** [comment]
@rdeutz @wilsonge this is ready from my perspective

**Comment by rdeutz** [comment]
@wilsonge go?

**Comment by wilsonge** [comment]
go

**Comment by brianteeman** [comment]
@rdeutz did I do something wrong on thee test change as it is still failing with the same error

**Comment by rdeutz** [comment]
no anything is good, its pulling still the old joomla-browser version, need to figure out how I can convince the system to load the new one

**Comment by rdeutz** [comment]
Seems there is something wrong, the installation doesn't work. I tried it locally and it ends with the follwing screen

installcest installjoomla fail

So the system-testing is right

**Comment by brianteeman** [comment]
i have done lots of test installs - will check again - maybe something slipped in doing the cs fixes

**Comment by brianteeman** [comment]
And drone is now happy

**Comment by wilsonge** [comment]
And merged :) thanks!
