### PR TITLE
Fix hiddenLabel and add hiddenLegend form attribute

### LINKED ISSUE #29709: [4.0b1] form attribute hiddenLabel not working as expected
### Steps to reproduce the issue
add form attribute to a form field:

```
hiddenLabel="false"
```

### Expected result
the label for the field should be displayed

### Actual result
the label for the field is hidden

### Additional comments
this attribute only acts on if the attribute is set in the form, NOT what value is set. This prevents overwriting a form field that has the label hidden by default.

### PR DESCRIPTION
**Pull request by Ruud68**
Pull Request for Issue #29611 and #29709  .

### Summary of Changes
1. This PR fixes #29709
2. This PR adds form attribute 'hiddenLegend' and fixes #29611 

the PR introduces a new hiddenLegend form attribute that can be set in the xml file as attribute for toggling the legend on any field) or in the layout file to give the attribute an initial value (defaults to true when not set)

### Testing Instructions
1.1 add form attribute hiddenLabel="false" to a form field
2.1 add a form field type Note to a config file
2.2 add form attribute hiddenLegend="false" to the 2.1 added field
2.3 add form attribute hiddenLegend="true" to a form field

### Expected result
1.1 the label for the form field should NOT ( = false)  be hidden
2.1 the legend for the Note field (which is the description that is part of the Note field) should not be displayed
2.2 the legend for the Note field should be DISPLAYED
2.3 the legend for the form field that you added the attribute to should be HIDDEN

### Actual result
whithout this PR:
1.1 the label for the form field IS hidden
2.1 the legend IS shown with the same information as the note itself
2.2 the legend IS shown with the same information as the note itself
2.3 the legend IS shown for the form field that you added the attribute to

### Documentation Changes Required
yes, same changes as made for the 'hiddenLabel' attribute

### CODE REVIEW

**Comment by brianteeman** [comment]
Not checked this yet but legend has a specific meaning which is not this so it would be better to use some other name

**Comment by Ruud68** [comment]
> Not checked this yet but legend has a specific meaning which is not this so it would be better to use some other name

I am dutch so all sounds good in English :)
If you have a better name please let me know

Legend: "the words written on or next to a picture, map, coin, etc., that explain what it is about or what the symbols on it mean"

**Comment by brianteeman** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend

whats wrong with note

**Comment by Ruud68** [comment]
> whats wrong with note

if users now that we mean this, then we are good I guess, your call. If it is okay with you the I refactor
Selection_002

**Comment by Ruud68** [comment]
But then again, that might be confusing when applying it to a note field where you then set hiddenNote... what are we hiding here, the note or the note field?
So maybe hiddenDescription? as that is what we are hiding in the code (description value)

**Comment by richard67** [comment]
> So maybe hiddenDescription? as that is what we are hiding in the code (description value)

Makes sense to me, "hiddenDescription". @brianteeman What do you think?

**Comment by Ruud68** [comment]
So just renamed legend to description. i also set the hiddenLabel to true on the Note field as this field doesn't have a label.
Let the testing begin :)

File: layouts/joomla/form/renderfield.php [hunk 1]
```diff
@@ -29,22 +29,25 @@
...
 	<div class="controls">
 		<?php echo $input; ?>
-		<?php if (!empty($description)) : ?>
-			<div id="<?php echo $id; ?>">
-				<small class="form-text text-muted">
-					<?php echo $description; ?>
-				</small>
-			</div>
+		<?php if (!$hideDescription) : ?>
+			<?php if (!empty($description)) : ?>
```
Comment (Quy) [inline layouts/joomla/form/renderfield.php]: Please consider combining lines 43-44 to reduce indentation level.

Comment (Ruud68) [reply layouts/joomla/form/renderfield.php]: Done

**Comment by SharkyKZ** [comment]
My 2c: introducing `hiddenLabel` attribute to base form field class might have been a mistake and same for this. If fields are misusing properties used in used in wrapper layout, they should come with their own layout.

**Comment by Ruud68** [comment]
@SharkyKZ using a seperate layout will not change the fact that everything goes through the renderer. What is basically wrong is that the renderer does more then render, it adds things that should be handled by the layout. (the description in this case). So when you remove that from the renderer, then you must refactor all (!) layout files to handle the description: that is a lot of code redundancy. This PR is not about refactoring all fields, it is about building and extending what is already there. changing layouts will most likely also break b/c as implemented layout overrides are then also impacted.

**Comment by Ruud68** [comment]
Working on 'fitting' my extensions into the Joomla 4.0 administrator UI.

Ran into this issue again where notes used to instruct users (you know, for a better UX) are totally useless and confusing as the notes contents are displayed twice...

trying to get some traction for this PR (you know: "hey extension devs, help us because you are the ones using it...")
screen shot 2020-09-17 at 09 42 51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29710">issues.joomla.org/tracker/joomla-cms/29710</a>.</sub>

**Comment by wilsonge** [comment]
I think this makes sense and can see from the screenshot above the justification. So merging on review. Thanks!

**Comment by Ruud68** [comment]
Thanks for merging!
