### PR TITLE
[6.1] Fix switching media type on field reload

### LINKED ISSUE #47432: [6.1.0 beta] Change media field type keeps initial hidden type value
### What happened?

There are new custom field types (audio, video, document). When I create a new field, chose one of the new types and change it again **before saving**, the initial type is kept.

## How to trigger it

  1. Create a new field and select type audio (don't save)
  2. Change it to video
  3. Fill in required options and save 
  4. Go to an article, tab options

The field view still shows the type "audio" with follow-up errors, such as not being able to chose video formats

### Version

6.1

### Expected result

Select videos in the article's field.

### Actual result

Image
Only audio files can be selected.

### System Information

_No response_

### Additional Comments

The problem is the hidded types field 
https://github.com/joomla/joomla-cms/blob/6.1-dev/plugins/fields/media/params/audio.xml#L33-L37

When the type is switched, the default value is kept.

### PR DESCRIPTION
**Pull request by HLeithner**
Pull Request resolves #47432 .

- [X] I read the [Generative AI policy](https://developer.joomla.org/generative-ai-policy.html) and my contribution is either not created with the help of AI or is compatible with the policy and GNU/GPL 2 or later.

### Summary of Changes
Unset the `types` parameter for the form field, this allows joomla to use the default form the xml.

### Testing Instructions
* Open the create screen for a new custom field
* Select type audio
* wait for reload
* Select type video
* wait for reload
* Save
* open article
* check media type

### Actual result BEFORE applying this Pull Request
The type is Audio instead of Video

### Expected result AFTER applying this Pull Request
The type is Video as expected.

### Link to documentations
Please select:
- [ ] Documentation link for guide.joomla.org: <link>
- [X] No documentation changes for guide.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

File: plugins/fields/media/src/Extension/Media.php [hunk 1]
```diff
@@ -36,10 +37,42 @@ final class Media extends FieldsPlugin implements SubscriberInterface
...
     }
 
+    /**
+     * Unset the fieldparams[types] parameter because the default value from the
+     * XML form get not overridden on field reload
+     *
+     * @param   PrepareDataEvent $event  The event instance.
+     *
+     * @return  void
+     * @since   6.1.0
```
Comment (tecpromotion) [inline plugins/fields/media/src/Extension/Media.php]:
```suggestion
     * @since  __DEPLOY_VERSION__
```
