### PR TITLE
Fix undefined var for ReCapture 2.0 API calls.

### LINKED ISSUE #6227: Recaptcha plugin throws "Undefined variable: challenge"
#### Steps to reproduce the issue

Just use recaptcha plugin with version 2.0 and error reporting on maximum. Or try to submit rcaptcha using AJAX.

#### Expected result

Successfully submitted form.

#### Actual result

I submit form using AJAX and due to this error I akways get the same response:

Notice:  Undefined variable: challenge in /mysite/plugins/captcha/recaptcha/recaptcha.php on line 158

This message will also pop, when error reporting is set to maximum.

#### System information (as much as possible)

Joomla 3.4, custom form.

#### Additional comments

Fix is very simple: $challenge variable should be defined any possible way. For example, you may add this line for version 2.0:

$challenge = $input->get('g-recaptcha-response', '', 'string');

### PR DESCRIPTION
**Pull request by PhilETaylor**
The Google ReCaptcha plugin supports 1.0 and 2.0 API calls. 

Reuse of the getResponse() method is made use of for both API versions but 2.0 doesnt need/require the `$challenge` 

This PR just silences strict warnings by setting the `$challenge` to ``null` and adds a tiny bit of additional documentation, cleans up a couple of other warnings and documents unused vars in method calls/signature

Closes #6227

### CODE REVIEW

File: plugins/captcha/recaptcha/recaptcha.php [hunk 1]
```diff
@@ -126,6 +126,8 @@ public function onCheckAnswer($code)
 				$spam      = ($challenge == null || strlen($challenge) == 0 || $response == null || strlen($response) == 0);
 				break;
 			case '2.0':
+				// Challenge Not needed in 2.0 but needed for getResponse call
+				$challenge = null;
 				$response = $input->get('g-recaptcha-response', '', 'string');
```
Comment (zero-24) [inline plugins/captcha/recaptcha/recaptcha.php]: @PhilETaylor can you add on space after: `$response` and `$spam` so the `=` are agline. Thanks!

**Comment by PhilETaylor** [comment]
added spaces as requested

**Comment by leetempest** [comment]
@test Tested with display errors on and all still works fine and no warnings/notices raised - captcha still works

File: plugins/captcha/recaptcha/recaptcha.php [hunk 2]
```diff
@@ -105,13 +105,13 @@ public function onDisplay($name, $id = 'dynamic_recaptcha_1', $class = '')
 	/**
 	 * Calls an HTTP POST function to verify if the user's guess was correct
 	 *
-	 * @param   string  $code  Answer provided by user.
+	 * @param   string  $code  Answer provided by user. @Deprecated and not needed for the current implementation
```
Comment (wilsonge) [inline plugins/captcha/recaptcha/recaptcha.php]: Can we keep this to not used rather than deprecated please. Don't forget there are some plugins out there using this plugin api who might use it. I wouldn't feel happy deprecating until i know how other captcha systems work

Comment (PhilETaylor) [inline plugins/captcha/recaptcha/recaptcha.php]: Its only a note, the actual function signature is unchanged, just sets the $code = null if its not passed. Deprecated is the wrong word, its just this plugin doesnt require the $code at all, but it has to be there to match the api.

Comment (PhilETaylor) [inline plugins/captcha/recaptcha/recaptcha.php]: I have removed the @deprecated now

**Comment by waader** [comment]
@test works, thanks!

**Comment by brianteeman** [comment]
Two tests setting RTC - Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6235">issues.joomla.org/joomla-cms/6235</a>.</sub>
