### PR TITLE
[5.4] Fix relative asset paths on Cassiopeia error page

### LINKED ISSUE #46610: Issue with custom 404 error page
### Steps to reproduce the issue

Based on the '[The 404 That Could: Why Your Joomla Site Deserves a Brilliant Error Page](https://magazine.joomla.org/all-issues/november-2025/the-404-that-could-why-your-joomla-site-deserves-a-brilliant-error-page)' article, I've tried to customize a 404 page.
However, I noticed some strange behavior in a certain situation that I can't seem to resolve.
I created a custom module as described in the guide, where I also inserted a custom text and an image.
Now, the behavior is as follows:
If I type http://yourdomain.com/thispagedoesnotexist -> the custom page appears correctly and the image is also visible.
If I type http://yourdomain.com/category/thispagedoesnotexist -> the custom error page does not load the image.
The image src is relative and the link ‘Back to homepage’ does not point to the homepage.

Any idea how to solve this issue?

### System information (as much as possible)

Joomla 6.0.1
PHP 8.3.29
Child template from Cassiopeia

### PR DESCRIPTION
**Pull request by krishnagandhicode**
Pull Request resolves #46610

- [x] I read the [Generative AI policy](https://developer.joomla.org/generative-ai-policy.html) and my contribution is either not created with the help of AI or is compatible with the policy and GNU/GPL 2 or later.

### Summary of Changes
~~Added a `<base>` tag to the Cassiopeia `error.php` template header.  This ensures that relative assets (like images in custom modules) load correctly when a 404 error  occurs on a nested URL.~~

~Added the onAfterRender event trigger to the exception handler.~

~404 exceptions bypassed the normal render pipeline, so the System - SEF plugin never got to run. 
now this fix ensures the event fires  allowing the SEf plugin to rewrite relative asset paths (like module  imagess) when a 404 occurs on a nested URL.~

Issue: 404 errors on nested URLs bypass the normal render pipeline, so the SEF plugin never runs to fix relative asset paths (like module imges).

Fix: Instead of modifying core exception files, it is handled entirely within the SEF plugin:

- Refactored the rewrite logic into a protected method.
- Added an onBeforeRespond listener to trigger the rewrite specifically for ErrorDocument pages.
- Added an internal flag to ensure it only executes once per request.

### Testing Instructions
Ensure URL Rewriting is enabled in Global Configuration and the .htaccess file is active.

Go to Administrator > Content > Site Modules
Create a "Custom" module 
Set the position to error-404 and 
go to menu assignemt and assign it to "All Pages" 
In the content editor, switch to code view and add an image with a relative path:
for eg: `Test Logo`
Visit http://yourdomain.com/thispagedoesnotexist -> the custom page appears and the image is also visible.
Visit http://yourdomain.com/category/thispagedoesnotexist -> the custom error page does not load the image.

### Actual result BEFORE applying this Pull Request
The image fails to load.

### Expected result AFTER applying this Pull Request
The image loads.

### Link to documentations
Please select:
- [ ] Documentation link for guide.joomla.org: <link>
- [x] No documentation changes for guide.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by krishnagandhicode** [comment]
> Hi @krishnagandhicode, did you check multi-lingual sites? and multi-lingual sites that are running from a sub-domain?
> 
> I ask because while I do confirm the BEFORE and AFTER condition for: The image fails to load and then The image loads correctly,
> 
> for the Home button, I can't seem to see any difference... (it could be simply that the Joomla router is handling things correctly...
> 
> Before I pass or fail this, I wanted to check with you.

Yes Uri::base() automatically grabs the right physical root URL, also for sub-domains as well.
router handles multilingual sites as well.

You are right about the home button, The original issue (# 46610) mentioned about this ("Back to home page") and I also tested using laragon with joomla in a subfolder so the button actually did break for me, I believe you tested using a hosted site - so it works fine for you.

if the main issue - relative image path is fixed with the patch - then the fix works :)

**Comment by richard67** [comment]
> > What you could try is to add `onBeforeRespond` listener to SEF plugin, and check for `if ($app->getDocument() instanceof \Joomla\CMS\Document\ErrorDocument){ ... }`.
> > An existing onAfterRender code will be need to move in to dedicated protected method. Potentially with internal flag to make sure it is called only once. This will be called then from onAfterRender and onBeforeRespond.
> 
> Thanks @Fedik I will refactor the SEF plugin now to use a protected method for onAfterRender and an internal flag to make sure it runs once per req.

@Fedik Would that mean it is a new feature? If so, the PR has to be made for the 6.2-dev branch.

**Comment by Fedik** [comment]
I mean, if we use `onBeforeRespond` listener we can take it as bug fix, there will be just code moving around SEF plugin.
But of course, RM still free to decide if they want it or it need to wait 6.1 bugfix or in 6.2.

And when we take another path and decide to add a new event dispatching, then it definitely a new feature.

**Comment by krishnagandhicode** [comment]
> I mean, if we use `onBeforeRespond` listener we can take it as bug fix, there will be just code moving around SEF plugin. But of course, RM still free to decide if they want it or it need to wait 6.1 bugfix or in 6.2.
> 
> And when we take another path and decide to add a new event dispatching, then it definitely a new feature.

Since you suggested it's okay as a bug fix, I've prepared the patch. It works and keeps everything contained within the SEF plugin.

Should I update the PR ?

File: plugins/system/sef/src/Extension/Sef.php [hunk 1]
```diff
@@ -320,6 +366,9 @@ function ($match) use ($base, $protocols) {
 
         // Use the replaced HTML body.
         $app->setBody($buffer);
+
+        // Mark as rewritten so it doesn't run again on BeforeRespond
+        $this->isRewritten = true;
```
Comment (Fedik) [inline plugins/system/sef/src/Extension/Sef.php]: Please place it directly after:
```
if ($this->isRewritten) {
     return;
}
```

Comment (Fedik) [reply plugins/system/sef/src/Extension/Sef.php]: This way when error happen during "rewriting" then the code will not be run again onBeforeResponse.
"Extra safety"

Comment (krishnagandhicode) [reply plugins/system/sef/src/Extension/Sef.php]: Done, moved right after the early return.

File: plugins/system/sef/src/Extension/Sef.php [hunk 2]
```diff
@@ -218,6 +227,45 @@ public function onAfterRender(AfterRenderEvent $event)
...
+     * Handle URL rewriting for error pages since they skip the normal render flow
+     *
+     * @param   BeforeRespondEvent $event  The event instance
+     *
+     * @return  void
+     */
+    public function onBeforeRespond(BeforeRespondEvent $event)
+    {
+        $app = $event->getApplication();
+        if (!$app->isClient('site')) {
```
Comment (richard67) [inline plugins/system/sef/src/Extension/Sef.php:249]:
```suggestion
        $app = $event->getApplication();

        if (!$app->isClient('site')) {
```
Code style improvement - empty line before control structure start.

**Comment by brianteeman** [comment]
The code works

Do all these new functions need to have `@ since` etc

File: plugins/system/sef/src/Extension/Sef.php [hunk 3]
```diff
@@ -35,6 +37,15 @@ final class Sef extends CMSPlugin implements SubscriberInterface
 {
     use SiteRouterAwareTrait;
 
+    /**
+     * Internal flag to make sure we don't process the buffer twice
+     *
+     * @var bool
+     *
+     * @since  5.4.0
```
Comment (brianteeman) [inline plugins/system/sef/src/Extension/Sef.php]: Sometimes a PR can take a while before it is merged so instead of merging code with a version specific version we instead write __DEPLOY_VERSION__ and then the vuild scripts will replace this with the actual version number on release

```suggestion
     * @since  __DEPLOY_VERSION__
```

Comment (krishnagandhicode) [reply plugins/system/sef/src/Extension/Sef.php]: Ohh wasn't aware of that, Thanks Brian.
