### PR TITLE
[5.0] Filter values of custom field, fix #42259

### LINKED ISSUE #42259: [5.0] Empty field value is rendering with added spaces in html so element is not :empty
### Steps to reproduce the issue
In J4 I have a newsflash module which displays a single article consisting of content from custom fields and uses a Newsflash_item override for display. The override has a div with the text 'Next Concert' used as the first text for the article displayed and just before the concert title. However, if there is a value in field #5 - e.g. "Sold Out" - then that would be shown instead of the 'Next Concert' but not if it's empty. The php is like this [extract]:

```
<div class="home-news-row article">
    <div class="home-concert-title">
        <div class="concert-message"><?php echo $item->jcfields[5]->value; ?></div><div class="our-next-concert">OUR NEXT CONCERT: </div><div class="concert-title d-md-inline-block"><h2><a href="<?php echo $item->link; ?>" title="read more about this concert"><?php echo $item->title; ?></a></h2></div>
    </div>
 </div>
````
and the CSS like this:

```
.home-news-row .concert-message:empty ~ .our-next-concert {
  background-color: var(--theme-contrast);
  color: var(--theme-dark);
  margin: 0 16px 8px 0;
  padding: 0.5rem 1rem 0.5rem;
  font-size: 1.75rem;
  font-weight: bold;
}
.home-news-row .concert-message:not(:empty) ~ .our-next-concert {
  display: none;
}
.home-news-row .concert-message,
.home-news-row .our-next-concert {
  display: inline-block;
}
.home-news-row .concert-message:empty {
  display: none;
}
```
### Expected result
In Joomla 4.4.0 it renders correctly:

j4-empty-div

### Actual result

j5-empty-div

Where you can see that not only is 'Our Next Concert' not displaying, but for some reason there is space and a new line added into the 'concert message' div. Coincidentally - or not - when I viewed the page source and copied and pasted the line into Word, I counted the number of spaces added to the html as being exactly the same number as the characters in "echo $item->jcfields[5]->value;" i.e. 31.

### System information (as much as possible)
Linux server
10.6.15-MariaDB-cll-lve-log 
PHP 8.1.24

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #42259 .

### Summary of Changes

Filter field value after onCustomFieldsPrepareField

### Testing Instructions
Please follow #42259
Create a Text field,
Save it,
And check the field rendering in the layout override.
Or use `dump($this->item->jcfields);` to see the field `->value`

### Actual result BEFORE applying this Pull Request
Value contain an empty space

### Expected result AFTER applying this Pull Request
Value is empty

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

Reference:
- https://github.com/joomla/joomla-cms/pull/41495

### CODE REVIEW

**Comment by Scrabble96** [comment]
The com_patchtester_4.3.1 doesn't seem to work in J5 so I can't test this. The error message message says:

An error has occurred while fetching the data from GitHub.

Error inserting pull request data into the database: Incorrect string value: '\xF0\x9F\xA5\x87 )...' for column `[mydomain]_joomlalatestversion`.`m2f0c_patchtester_pulls`.`description` at row 13

**Comment by fgsw** [comment]
No Problem using Patchtester 4.3.1 in J5.

**Comment by Scrabble96** [comment]
> No Problem using Patchtester 4.3.1 in J5.

Can you confirm what needs to be checked/ticked when I get an access token? Is it just the default that the link from the Patchtester checks? I've installed it on a brand new installation of J5 on a brand new subdomain on a new database.

I uninstalled it, logged out, logged back in and installed it again. Same result.

**Comment by fgsw** [comment]
pt1
pt2
pt3

**Comment by Scrabble96** [comment]
All those settings in Joomla are correct. What I meant was, what do I check/tick when I request an authentication token on Github at github.com/settings/tokens? I tried on another test site that had been updated from 4.4.0 to 5.0. Same result. It has public_repo, repo:status selected at the moment.

**Comment by fgsw** [comment]
pt-token

**Comment by angieradtke** [comment]
I have tested this item :red_circle: unsuccessfully on 4143e6b9c0c207305c2c36efe24f49b57bb6e196<br /><br />Thanks Fedir, works as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42285">issues.joomla.org/tracker/joomla-cms/42285</a>.</sub>

**Comment by angieradtke** [comment]
I have tested this item :white_check_mark: successfully on 4143e6b9c0c207305c2c36efe24f49b57bb6e196<br /><br />Thanks Fedir, works as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42285">issues.joomla.org/tracker/joomla-cms/42285</a>.</sub>

**Comment by angieradtke** [comment]
I have tested this item :white_check_mark: successfully on 4143e6b9c0c207305c2c36efe24f49b57bb6e196<br /><br />Thanks Fedir, works as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42285">issues.joomla.org/tracker/joomla-cms/42285</a>.</sub>

**Comment by HLeithner** [comment]
@Scrabble96 can you please test this pr, simple use the prebuilt packages from https://artifacts.joomla.org/drone/joomla/joomla-cms/5.0-dev/42285/downloads/71682

**Comment by Fedik** [comment]
@korenevskiy nope, what will hapen when value is `'0'`?

**Comment by korenevskiy** [comment]
> @korenevskiy nope, what will hapen when value is `'0'`?

You right!

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4143e6b9c0c207305c2c36efe24f49b57bb6e196<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42285">issues.joomla.org/tracker/joomla-cms/42285</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42285">issues.joomla.org/tracker/joomla-cms/42285</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Comment by angieradtke** [comment]
Do we need this Fix in 4.4 as well?

**Comment by HLeithner** [comment]
No because we changed the plugin trigger code in 5.0 which leads to this issue.

**Comment by angieradtke** [comment]
ah  ok - understand , thanks

**Comment by Scrabble96** [comment]
> @Scrabble96 can you please test this pr, simple use the prebuilt packages from https://artifacts.joomla.org/drone/joomla/joomla-cms/5.0-dev/42285/downloads/71682

Hi @HLeithner - I've just got around to testing this. It works fine. Thank you for fixing this.

File: administrator/components/com_fields/src/Helper/FieldsHelper.php [hunk 1]
```diff
@@ -227,7 +227,10 @@ function ($f) {
                     ]))->getArgument('result', []);
 
                     if (\is_array($value)) {
-                        $value = implode(' ', $value);
+                        $value = array_filter($value, function ($v) {
```
Comment (laoneo) [inline administrator/components/com_fields/src/Helper/FieldsHelper.php:230]: As array_filter removes all empty values when no callback is provided. Did you do it on purpose with a callback?

File: administrator/components/com_fields/src/Helper/FieldsHelper.php [hunk 2]
```diff
@@ -227,7 +227,10 @@ function ($f) {
...
+                            return $v !== '' && $v !== null;
+                        });
+                        $value = $value ? implode(' ', $value) : '';
```
Comment (laoneo) [inline administrator/components/com_fields/src/Helper/FieldsHelper.php:233]: Would not a trim be enough?

**Comment by Fedik** [comment]
@laoneo please check my previous comment https://github.com/joomla/joomla-cms/pull/42285#issuecomment-1794543806
`trim` also a bad idea, it will remove "white space" value

**Comment by laoneo** [comment]
Thanks for the info

**Comment by Scrabble96** [comment]
Silly question, perhaps, but can whatever was done to change it from J4.4.0 to J.5.0 just be reversed, rather than adding yet more code?

**Comment by Fedik** [comment]
We have updated old events APi to new :wink:
