### PR TITLE
[6.1] Fix workflow graph strings and assets

### LINKED ISSUE #47224: [6.1] workflow graph strings and assets
### Steps to reproduce the issue
Do NOT enable workflows
Open an article for editing
View the source of the page and check css loaded and the contents of `<script type="application/json" class="joomla-script-options loaded"`

### Expected result
Nothing related to Workflow graph is included

### Actual result
`<link href="/media/com_workflow/css/workflow-graph-client.min.css?4f6614" rel="stylesheet">`
`<script src="/media/com_workflow/js/workflow-graph-client.min.js?4f6614" type="module"></script>`

`"COM_WORKFLOW_GRAPH":"COM_WORKFLOW_GRAPH","COM_WORKFLOW_GRAPH_ADD_STAGE":"COM_WORKFLOW_GRAPH_ADD_STAGE","COM_WORKFLOW_GRAPH_ADD_STAGE_DIALOG_OPENED":"COM_WORKFLOW_GRAPH_ADD_STAGE_DIALOG_OPENED","COM_WORKFLOW_GRAPH_ADD_TRANSITION_DIALOG_OPENED":"COM_WORKFLOW_GRAPH_ADD_TRANSITION_DIALOG_OPENED","COM_WORKFLOW_GRAPH_ADD_TRANSITION":"COM_WORKFLOW_GRAPH_ADD_TRANSITION","COM_WORKFLOW_GRAPH_API_NOT_SET":"COM_WORKFLOW_GRAPH_API_NOT_SET","COM_WORKFLOW_GRAPH_BACKGROUND":"COM_WORKFLOW_GRAPH_BACKGROUND","COM_WORKFLOW_GRAPH_CANVAS_DESCRIPTION":"COM_WORKFLOW_GRAPH_CANVAS_DESCRIPTION","COM_WORKFLOW_GRAPH_CANVAS_LABEL":"COM_WORKFLOW_GRAPH_CANVAS_LABEL","COM_WORKFLOW_GRAPH_CANVAS_VIEW_CONTROLS":"COM_WORKFLOW_GRAPH_CANVAS_VIEW_CONTROLS","COM_WORKFLOW_GRAPH_CLEAR_SELECTION":"COM_WORKFLOW_GRAPH_CLEAR_SELECTION","COM_WORKFLOW_GRAPH_CLOSE_ACTIONS_MENU":"COM_WORKFLOW_GRAPH_CLOSE_ACTIONS_MENU","COM_WORKFLOW_GRAPH_CONTROLS":"COM_WORKFLOW_GRAPH_CONTROLS","COM_WORKFLOW_GRAPH_CREATING_TRANSITION":"COM_WORKFLOW_GRAPH_CREATING_TRANSITION","COM_WORKFLOW_GRAPH_DEFAULT":"COM_WORKFLOW_GRAPH_DEFAULT","COM_WORKFLOW_GRAPH_DISABLED":"COM_WORKFLOW_GRAPH_DISABLED","COM_WORKFLOW_GRAPH_EDIT_ITEM":"COM_WORKFLOW_GRAPH_EDIT_ITEM","COM_WORKFLOW_GRAPH_EDIT_STAGE":"COM_WORKFLOW_GRAPH_EDIT_STAGE","COM_WORKFLOW_GRAPH_EDIT_TRANSITION":"COM_WORKFLOW_GRAPH_EDIT_TRANSITION","COM_WORKFLOW_GRAPH_ENABLED":"COM_WORKFLOW_GRAPH_ENABLED","COM_WORKFLOW_GRAPH_ERROR_API_RETURNED_ERROR":"COM_WORKFLOW_GRAPH_ERROR_API_RETURNED_ERROR","COM_WORKFLOW_GRAPH_ERROR_CSRF_TOKEN_NOT_SET":"COM_WORKFLOW_GRAPH_ERROR_CSRF_TOKEN_NOT_SET","COM_WORKFLOW_GRAPH_ERROR_EXTENSION_NOT_SET":"COM_WORKFLOW_GRAPH_ERROR_EXTENSION_NOT_SET","COM_WORKFLOW_GRAPH_ERROR_FAILED_TO_UPDATE_STAGE_POSITIONS":"COM_WORKFLOW_GRAPH_ERROR_FAILED_TO_UPDATE_STAGE_POSITIONS","COM_WORKFLOW_GRAPH_ERROR_FETCHING_MODEL":"COM_WORKFLOW_GRAPH_ERROR_FETCHING_MODEL","COM_WORKFLOW_GRAPH_ERROR_INVALID_ID":"COM_WORKFLOW_GRAPH_ERROR_INVALID_ID","COM_WORKFLOW_GRAPH_ERROR_INVALID_POSITION_DATA":"COM_WORKFLOW_GRAPH_ERROR_INVALID_POSITION_DATA","COM_WORKFLOW_GRAPH_ERROR_INVALID_STAGE_POSITIONS":"COM_WORKFLOW_GRAPH_ERROR_INVALID_STAGE_POSITIONS","COM_WORKFLOW_GRAPH_ERROR_NOT_AUTHENTICATED":"COM_WORKFLOW_GRAPH_ERROR_NOT_AUTHENTICATED","COM_WORKFLOW_GRAPH_ERROR_NO_PERMISSION":"COM_WORKFLOW_GRAPH_ERROR_NO_PERMISSION","COM_WORKFLOW_GRAPH_ERROR_REQUEST_FAILED":"COM_WORKFLOW_GRAPH_ERROR_REQUEST_FAILED","COM_WORKFLOW_GRAPH_ERROR_STAGES_NOT_FOUND":"COM_WORKFLOW_GRAPH_ERROR_STAGES_NOT_FOUND","COM_WORKFLOW_GRAPH_ERROR_STAGE_DEFAULT_CANT_DELETED":"COM_WORKFLOW_GRAPH_ERROR_STAGE_DEFAULT_CANT_DELETED","COM_WORKFLOW_GRAPH_ERROR_STAGE_HAS_TRANSITIONS":"COM_WORKFLOW_GRAPH_ERROR_STAGE_HAS_TRANSITIONS","COM_WORKFLOW_GRAPH_ERROR_UNKNOWN":"COM_WORKFLOW_GRAPH_ERROR_UNKNOWN","COM_WORKFLOW_GRAPH_ERROR_WORKFLOW_ID_NOT_SET":"COM_WORKFLOW_GRAPH_ERROR_WORKFLOW_ID_NOT_SET","COM_WORKFLOW_GRAPH_ERROR_WORKFLOW_NOT_FOUND":"COM_WORKFLOW_GRAPH_ERROR_WORKFLOW_NOT_FOUND","COM_WORKFLOW_GRAPH_FIT_VIEW":"COM_WORKFLOW_GRAPH_FIT_VIEW","COM_WORKFLOW_GRAPH_FOCUS_TYPE_CHANGE":"COM_WORKFLOW_GRAPH_FOCUS_TYPE_CHANGE","COM_WORKFLOW_GRAPH_LOADING":"COM_WORKFLOW_GRAPH_LOADING","COM_WORKFLOW_GRAPH_MINIMAP_HIDE":"COM_WORKFLOW_GRAPH_MINIMAP_HIDE","COM_WORKFLOW_GRAPH_MINIMAP_LABEL":"COM_WORKFLOW_GRAPH_MINIMAP_LABEL","COM_WORKFLOW_GRAPH_MINIMAP_SHOW":"COM_WORKFLOW_GRAPH_MINIMAP_SHOW","COM_WORKFLOW_GRAPH_MOVE_STAGE":"COM_WORKFLOW_GRAPH_MOVE_STAGE","COM_WORKFLOW_GRAPH_MOVE_VIEW":"COM_WORKFLOW_GRAPH_MOVE_VIEW","COM_WORKFLOW_GRAPH_NAVIGATE_NODES":"COM_WORKFLOW_GRAPH_NAVIGATE_NODES","COM_WORKFLOW_GRAPH_OPEN_ACTIONS_MENU":"COM_WORKFLOW_GRAPH_OPEN_ACTIONS_MENU","COM_WORKFLOW_GRAPH_SELECTION_CLEARED":"COM_WORKFLOW_GRAPH_SELECTION_CLEARED","COM_WORKFLOW_GRAPH_SELECT_ITEM":"COM_WORKFLOW_GRAPH_SELECT_ITEM","COM_WORKFLOW_GRAPH_SHORTCUTS":"COM_WORKFLOW_GRAPH_SHORTCUTS","COM_WORKFLOW_GRAPH_SHORTCUTS_TITLE":"COM_WORKFLOW_GRAPH_SHORTCUTS_TITLE","COM_WORKFLOW_GRAPH_STAGE":"COM_WORKFLOW_GRAPH_STAGE","COM_WORKFLOW_GRAPH_STAGES":"COM_WORKFLOW_GRAPH_STAGES","COM_WORKFLOW_GRAPH_STAGE_ACTIONS":"COM_WORKFLOW_GRAPH_STAGE_ACTIONS","COM_WORKFLOW_GRAPH_STAGE_COUNT":"COM_WORKFLOW_GRAPH_STAGE_COUNT","COM_WORKFLOW_GRAPH_STAGE_DESCRIPTION":"COM_WORKFLOW_GRAPH_STAGE_DESCRIPTION","COM_WORKFLOW_GRAPH_STAGE_POSITIONS_UPDATED":"COM_WORKFLOW_GRAPH_STAGE_POSITIONS_UPDATED","COM_WORKFLOW_GRAPH_STAGE_REF":"COM_WORKFLOW_GRAPH_STAGE_REF","COM_WORKFLOW_GRAPH_STAGE_SELECTED":"COM_WORKFLOW_GRAPH_STAGE_SELECTED","COM_WORKFLOW_GRAPH_STAGE_STATUS_ENABLED":"COM_WORKFLOW_GRAPH_STAGE_STATUS_ENABLED","COM_WORKFLOW_GRAPH_STAGE_STATUS_DISABLED":"COM_WORKFLOW_GRAPH_STAGE_STATUS_DISABLED","COM_WORKFLOW_GRAPH_STATUS":"COM_WORKFLOW_GRAPH_STATUS","COM_WORKFLOW_GRAPH_TRANSITION":"COM_WORKFLOW_GRAPH_TRANSITION","COM_WORKFLOW_GRAPH_TRANSITIONS":"COM_WORKFLOW_GRAPH_TRANSITIONS","COM_WORKFLOW_GRAPH_TRANSITION_ACTIONS":"COM_WORKFLOW_GRAPH_TRANSITION_ACTIONS","COM_WORKFLOW_GRAPH_TRANSITION_COUNT":"COM_WORKFLOW_GRAPH_TRANSITION_COUNT","COM_WORKFLOW_GRAPH_TRANSITION_DESCRIPTION":"COM_WORKFLOW_GRAPH_TRANSITION_DESCRIPTION","COM_WORKFLOW_GRAPH_TRANSITION_PATH":"COM_WORKFLOW_GRAPH_TRANSITION_PATH","COM_WORKFLOW_GRAPH_TRANSITION_REF":"COM_WORKFLOW_GRAPH_TRANSITION_REF","COM_WORKFLOW_GRAPH_TRANSITION_SELECTED":"COM_WORKFLOW_GRAPH_TRANSITION_SELECTED","COM_WORKFLOW_GRAPH_TRANSITION_STATUS_ENABLED":"COM_WORKFLOW_GRAPH_TRANSITION_STATUS_ENABLED","COM_WORKFLOW_GRAPH_TRANSITION_STATUS_DISABLED":"COM_WORKFLOW_GRAPH_TRANSITION_STATUS_DISABLED","COM_WORKFLOW_GRAPH_TRASH_ITEM":"COM_WORKFLOW_GRAPH_TRASH_ITEM","COM_WORKFLOW_GRAPH_TRASH_STAGE":"COM_WORKFLOW_GRAPH_TRASH_STAGE","COM_WORKFLOW_GRAPH_TRASH_STAGE_CONFIRM":"COM_WORKFLOW_GRAPH_TRASH_STAGE_CONFIRM","COM_WORKFLOW_GRAPH_TRASH_STAGE_FAILED":"COM_WORKFLOW_GRAPH_TRASH_STAGE_FAILED","COM_WORKFLOW_GRAPH_TRASH_TRANSITION":"COM_WORKFLOW_GRAPH_TRASH_TRANSITION","COM_WORKFLOW_GRAPH_TRASH_TRANSITION_CONFIRM":"COM_WORKFLOW_GRAPH_TRASH_TRANSITION_CONFIRM","COM_WORKFLOW_GRAPH_TRASH_TRANSITION_FAILED":"COM_WORKFLOW_GRAPH_TRASH_TRANSITION_FAILED","COM_WORKFLOW_GRAPH_UNSAVED_CHANGES":"COM_WORKFLOW_GRAPH_UNSAVED_CHANGES","COM_WORKFLOW_GRAPH_UPDATE_STAGE_POSITION_FAILED":"COM_WORKFLOW_GRAPH_UPDATE_STAGE_POSITION_FAILED","COM_WORKFLOW_GRAPH_UP_TO_DATE":"COM_WORKFLOW_GRAPH_UP_TO_DATE","COM_WORKFLOW_GRAPH_WORKFLOWS_EDIT":"COM_WORKFLOW_GRAPH_WORKFLOWS_EDIT","COM_WORKFLOW_GRAPH_ZOOM_IN":"COM_WORKFLOW_GRAPH_ZOOM_IN","COM_WORKFLOW_GRAPH_ZOOM_OUT":"COM_WORKFLOW_GRAPH_ZOOM_OUT"`

### PR DESCRIPTION
**Pull request by Vikash-Kumar-23**
Pull Request resolves #47224

- [x] I read the [Generative AI policy](https://developer.joomla.org/generative-ai-policy.html) and my contribution is either not created with the help of AI or is compatible with the policy and GNU/GPL 2 or later.

### Testing Instructions
Install Joomla 6.1-dev.

Go to Content -> Articles -> Options.

Set Enable Workflows to No.

Open any article for editing.

View the page source (Ctrl+U) and search for workflow-graph.

Result: No assets or strings should be found.

Return to Options and set Enable Workflows to Yes.

Refresh the article edit page and view source again.

Result: workflow-graph-client assets should now be present, confirming the feature still works when enabled.

### Actual result BEFORE applying this Pull Request
Even if workflow_enabled is off :
Screenshot (1582)
Screenshot (1584)

### Expected result AFTER applying this Pull Request
if workflow_enabled is off:
Screenshot (1586)

if workflow_enabled is on:
Screenshot (1588)

### Link to documentations
Please select:
- [x] Documentation link for guide.joomla.org: <link>
- [x] No documentation changes for guide.joomla.org needed

- [x] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

File: libraries/src/MVC/Model/WorkflowBehaviorTrait.php [hunk 1]
```diff
@@ -340,7 +340,10 @@ protected function addTransitionField(Form $form, $data)
         $field->addAttribute('type', $this->workflowEnabled ? 'transition' : 'hidden');
         $field->addAttribute('label', 'COM_CONTENT_WORKFLOW_STAGE');
         $field->addAttribute('extension', $extension);
-        $field->addAttribute('layout', 'joomla.form.field.groupedlist-transition');
+        
+        if ($this->workflowEnabled) {
```
Comment (richard67) [inline libraries/src/MVC/Model/WorkflowBehaviorTrait.php]:
```suggestion

        if ($this->workflowEnabled) {
```
Please fix this code style error, and if possible adjust your editor or IDE so it shows white space and tabulators in the editor, and switch off automatic indentation to avoid such errors. Thanks in advance.
