### PR TITLE
[4.0] Fix Category select is missing/broken for fields

### LINKED ISSUE #24782: [4.0][com_fields] Category select is missing/broken for fields
From #24711
> Also, it seems like choosing a category for a custom field currently seems broken in 4.0-dev generally, not only in this branch? Seems to be caused by an exception being thrown at
https://github.com/joomla/joomla-cms/blob/e2abc0993baa4e5abb5a3166c56f3888c278c40c/administrator/components/com_fields/Model/FieldModel.php#L989
This needs to be investigated, but it ain't part of this PR. Just dropping this note here, because I think testers will stumble accross not being able to set a category for a custom field.

Creating a separate issue for this to make sure we fix this :-)

### PR DESCRIPTION
**Pull request by continga**
Pull Request for Issue #24782

### Summary of Changes

The problem is that we were passing $section to the category service, which always ends up bailing with a SectionNotFoundException - while we just wanted to get all categories at this point.

It basically reverts the change made to this line in commit https://github.com/joomla/joomla-cms/commit/c7789733ec2c04fecbe497391af80b149f7f0596 but that is a merge commit
and none of the merged parents have that change, and the commit does not give an explanation why
that change is needed. It is not needed at all from my point of view, so reverting it here.

This fixes #24782 and should not have any side effects, as the CategoryService is being instanciated
with a correct context (the component), so passing the $section is not needed. We want all categories.

### Testing Instructions

Try to create a new Custom Field in e.g. the Content group.

### Expected result

You should be able to set a category for that field on the right hand side.

### Actual result

Without this change, you are not able to set a category.

### Additional info

Poking @wilsonge You are the author of the original commit creating the problem, do you remember why you changed that line, and are you OK with this PR changing it back, or do you see any problems?

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Categories support different content types (sections) per component (See https://github.com/joomla/joomla-cms/pull/17769). So I don't think this is correct. Looks like Category services in components need to be updated to include the section. Either that or we could try to load categories with and without the section before bailing out.

**Comment by SharkyKZ** [comment]
Categories support different content types (sections) per component (See https://github.com/joomla/joomla-cms/pull/17769). So I don't think this is correct. Looks like Category services in components need to be updated to include the section. Either that or we should try to load categories with and without the section before failing.

**Comment by wilsonge** [comment]
@SharkyKZ got it. it was an attempted port of the PR he mentions. I definitely might have made a mess of it in the conflicts though

**Comment by continga** [comment]
Okay, I have changed my PR to first check on component+section, and if that hasn't been found, only then search for just the component. Can you please take a look again @SharkyKZ and @wilsonge ?

Additionally, I noticed the following: Looking at the changes made in #17769, I see that in the FieldsModel, we are still using the (old?) Categories instance: https://github.com/joomla/joomla-cms/blob/501dfad2de50584107ffbfd0448867ee45617c39/administrator/components/com_fields/Model/FieldsModel.php#L199

Same for the fields default template: https://github.com/joomla/joomla-cms/blob/501dfad2de50584107ffbfd0448867ee45617c39/administrator/components/com_fields/tmpl/fields/default.php#L35

I am wondering why we then are using the (new?) ComponentObject only for the FieldModel: https://github.com/joomla/joomla-cms/blob/501dfad2de50584107ffbfd0448867ee45617c39/administrator/components/com_fields/Model/FieldModel.php#L959

Maybe we should switch the other two cases to be using the (new?) ComponentObject too, or maybe switch the FieldModel to use the (old?) Categories instance? Instead of now having 2 different ways of doing the same thing in the same component...

File: administrator/components/com_fields/Model/FieldModel.php [hunk 1]
```diff
@@ -946,29 +946,54 @@ protected function preprocessForm(Form $form, $data, $group = 'content')
...
-			{
-				$form->setFieldAttribute('assigned_cat_ids', 'extension', $component);
-			}
-			else
-			{
-				$form->removeField('assigned_cat_ids');
+				// Try to get the categories for this component and section
+				try
+				{
+					$cat = $componentObject->getCategory([], $section ?: '');
```
Comment (SharkyKZ) [inline administrator/components/com_fields/Model/FieldModel.php:966]: If section categories are found they should be returned. Otherwise they're overwritten by component categories.

Comment (continga) [reply administrator/components/com_fields/Model/FieldModel.php:966]: lol, of course you are right, fixed!

**Comment by wilsonge** [comment]
> Maybe we should switch the other two cases to be using the (new?) ComponentObject too, or maybe switch the FieldModel to use the (old?) Categories instance? Instead of now having 2 different ways of doing the same thing in the same component...

Yup it should be swapped over to be consistently using component objects

**Comment by wilsonge** [comment]
Also something seems weird here. If section doesn't exist it should be able to handle the empty string fine - because it is the default parameter https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Categories/CategoryServiceTrait.php#L43

**Comment by wilsonge** [comment]
Spent some time debugging to understand. Apparently article comes back as a valid section which is kinda stupid. But it's a much riskier b/c affecting change to try and fix that so this will do. Thanks!
