### PR TITLE
Fix gh-6397 isSafeFile fails on deeply nested $_FILES

### LINKED ISSUE #6397: JFilterInput::isSafeFile() fail on very deep $_FILES array
I have complex form with multiple files upload, in diferent groups,
and in call $app->input->files j3.4 produce 100 warnings:
```
Warning: strstr() expects parameter 1 to be string, array given in libraries/joomla/filter/input.php on line 433
Warning: explode() expects parameter 2 to be string, array given in libraries/joomla/filter/input.php on line 442
Warning: array_reverse() expects parameter 1 to be array, null given in libraries/joomla/filter/input.php on line 443
Warning: array_pop() expects parameter 1 to be array, null given in libraries/joomla/filter/input.php on line 444
Warning: array_map(): Argument #2 should be an array in libraries/joomla/filter/input.php on line 445
Warning: in_array() expects parameter 2 to be array, null given in libraries/joomla/filter/input.php on line 453
Warning: in_array() expects parameter 2 to be array, null given in libraries/joomla/filter/input.php on line 453
Warning: in_array() expects parameter 2 to be array, null given in libraries/joomla/filter/input.php on line 453
Warning: in_array() expects parameter 2 to be array, null given in libraries/joomla/filter/input.php on line 453
Warning: in_array() expects parameter 2 to be array, null given in libraries/joomla/filter/input.php on line 453
```
all these related how `JFilterInput::isSafeFile() ` works.

**how to reproduce** 
it a bit tricky :smile:
simplest way, make fake _FILES, in way how _FILES looks in my form.:
```php
$_FILES = array(
	'jform' => array(
		'name' => array(
			'document' => '',
			'files' => array(
				'files0' => array(
					'file' => ''
				),
				'files1' => array(
					'file' => ''
				),
				'files2' => array(
					'file' => ''
				),
				'files3' => array(
					'file' => ''
				)
			),
			'images' => array(
				'images0' => array(
					'file' => ''
				),
				'images1' => array(
					'file' => ''
				)
			)
		),
		'type' => array(
			'document' => '',
			'files' => array(
				'files0' => array(
					'file' => ''
				),
				'files1' => array(
					'file' => ''
				),
				'files2' => array(
					'file' => ''
				),
				'files3' => array(
					'file' => ''
				)
			),
			'images' => array(
				'images0' => array(
					'file' => ''
				),
				'images1' => array(
					'file' => ''
				)
			)
		),
		'tmp_name' => array(
			'document' => '',
			'files' => array(
				'files0' => array(
					'file' => ''
				),
				'files1' => array(
					'file' => ''
				),
				'files2' => array(
					'file' => ''
				),
				'files3' => array(
					'file' => ''
				)
			),
			'images' => array(
				'images0' => array(
					'file' => ''
				),
				'images1' => array(
					'file' => ''
				)
			)
		),
		'error' => array(
			'document' => 4,
			'files' => array(
				'files0' => array(
					'file' => 4
				),
				'files1' => array(
					'file' => 4
				),
				'files2' => array(
					'file' => 4
				),
				'files3' => array(
					'file' => 4
				)
			),
			'images' => array(
				'images0' => array(
					'file' => 4
				),
				'images1' => array(
					'file' => 4
				)
			)
		),
		'size' => array(
			'document' => 0,
			'files' => array(
				'files0' => array(
					'file' => 0
				),
				'files1' => array(
					'file' => 0
				),
				'files2' => array(
					'file' => 0
				),
				'files3' => array(
					'file' => 0
				)
			),
			'images' => array(
				'images0' => array(
					'file' => 0
				),
				'images1' => array(
					'file' => 0
				)
			)
		),
	)
);
$app = JFactory::getApplication();
$files = $app->input->files->get('jform');
echo '<pre>';
print_r($files['document']);
echo '</pre>';
```

**expected result**
just output from print_r  $files['document']
```
Array
(
    [name] => 
    [type] => 
    [tmp_name] => 
    [error] => 4
    [size] => 0
)
```

**actual result**
1000 PHP warnings
and only then output from print_r

### PR DESCRIPTION
**Pull request by nikosdion**
This PR fixes gh-6397 "JFilterInput::isSafeFile() fail on very deep $_FILES array"
# Testing instructions
- Download and install the Joomla! 3 sample component from https://github.com/joomla/Joomla-3.2-Hello-World-Component/archive/step-10-adding-decorations-to-the-backend.zip
- Open the file administrator/components/com_helloworld/models/forms/helloworld.xml and add the following before the closing `</fieldset>`

``` xml
        <field type="file" name="document"  label="Document" />
        <fields name="files">
            <fields name="files0">
                <field type="file" name="file"  label="File 1" />
            </fields>
            <fields name="files1">
                <field type="file" name="file"  label="File 2" />
            </fields>
            <fields name="files2">
                <field type="file" name="file"  label="File 3" />
            </fields>
        </fields>
        <fields name="images">
            <fields name="images0">
                <field type="file" name="file"  label="Images 1" />
            </fields>
            <fields name="images1">
                <field type="file" name="file"  label="Images 2" />
            </fields>
        </fields>
```
- Open the file administrator/components/com_helloworld/controllers/helloworld.php and add the following between the two curly braces

``` php
    public function save($key = null, $urlVar = null)
    {
        $app = JFactory::getApplication();
        $files = $app->input->files->get('jform');

        die('CHECK');

        return parent::save($key, $urlVar); // TODO: Change the autogenerated stub
    }
```
- Go to Global Configuration and set Error Reporting to Development
- Go to Components, Hello World and click on the "Hello, world" link to edit the item.
- Click each file selection field and choose a small image from your computer. It's best to select files where each one is less than 100Kb to prevent upload issues with PHP itself.
- Click on the Save & Close button

**Result before the patch**
A lot of PHP warnings

**Result after the patch**
No PHP warnings, just the word "CHECK" printed on your page
# Technical notes

There were two corrective actions taken:
- The safe file check was moved into get(). This may have a performance impact on unoptimised code calling $app->input->files->get() repeatedly over the same files, but there's no work around due to the way PHP reports uploaded files. Sorry :(
- The JFilterInput::isSafeFile method was modified to handle nested file arrays, either in the raw $_FILES format or as nested arrays of file descriptors (these are the only two possible variations that exist)

Signed-off-by: Nicholas K. Dionysopoulos nicholas@akeebabackup.com

### CODE REVIEW

**Comment by Fedik** [comment]
thanks @nikosdion 

**test**
work good

**Comment by brianteeman** [comment]
@nikosdion travis isnt happy<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6454">issues.joomla.org/joomla-cms/6454</a>.</sub>

**Comment by nikosdion** [comment]
It's not really my fault. Travis chokes on a line I copied verbatim from JInputFiles. Apparently core code doesn't conform to the core coding standards... Anyway, I updated the PR to make Travis a happy chap.

**Comment by brianteeman** [comment]
I only said travis wasnt happy. I did not apportion blame :)

**Comment by nikosdion** [comment]
I know, Brian. Let me and Michael complain about the state of the core :)

File: libraries/joomla/filter/input.php [hunk 1]
```diff
@@ -327,14 +327,13 @@ public static function checkAttribute($attrSubSet)
...
 	 * The options you can define are:
-	 *
-	 * null_byte                   Prevent files with a null byte in their name (buffer overflow attack)
-	 * forbidden_extensions        Do not allow these strings anywhere in the file's extension
-	 * php_tag_in_content          Do not allow <?php tag in content
-	 * shorttag_in_content         Do not allow short tag <? in content
-	 * shorttag_extensions         Which file extensions to scan for short tags in content
-	 * fobidden_ext_in_content     Do not allow forbidden_extensions anywhere in content
-	 * php_ext_content_extensions  Which file extensions to scan for .php in content
+	 * null_byte Prevent files with a null byte in their name (buffer overflow attack)
```
Comment (wilsonge) [inline libraries/joomla/filter/input.php]: Can we realign this please?

**Comment by nikosdion** [comment]
@wilsonge I fixed the alignment

**Comment by Kubik-Rubik** [comment]
@cheesegrits We need your feedback ASAP. Thanks!
