### PR TITLE
Filter isInstalled query for components, fix #6697

### LINKED ISSUE #6697: False positive for isInstalled() due to querying element
I'm not 100% sure this is a bug, but here goes:

#### Steps to reproduce the issue
1) Uninstall weblinks
2) Install OSMap ([https://github.com/OSTraining/OSMap/releases/download/v3.0.2/com_osmap_free_3.0.2.zip](https://github.com/OSTraining/OSMap/releases/download/v3.0.2/com_osmap_free_3.0.2.zip ""))
3) In the administrator control panel (administrator/index.php), you should see an internal server error for the "Site Information" module:
> Error 1146: Table '_weblinks' doesn't exist SQL=SELECT COUNT(id) AS count_links FROM _weblinks WHERE state = 1

#### Expected result
The "Site Information" module should work. I'm guessing the error should be caught and it should degrade gracefully.

#### Actual result
Error 1146: Table '_weblinks' doesn't exist SQL=SELECT COUNT(id) AS count_links FROM _weblinks WHERE state = 1

#### Additional comments

It's because of this code:
[https://github.com/joomla/joomla-cms/blob/3.4.1/libraries/cms/component/helper.php#L102](https://github.com/joomla/joomla-cms/blob/3.4.1/libraries/cms/component/helper.php#L102 "")

It's querying for the "element", however the weblinks plugin in OSMap uses an element of "com_weblinks" because it's a weblinks plugin.

### PR DESCRIPTION
**Pull request by mbabker**
Does what we can to fix #6697 by filtering the query on components only.  And if someone else is using `com_weblinks` as a component name, well, that's a condition we can't account for in code.

### CODE REVIEW

**Comment by brianteeman** [comment]
we now have a second proposed fix #6701 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6698">issues.joomla.org/joomla-cms/6698</a>.</sub>

**Comment by Bakual** [comment]
Use this one. Didn't see it.

Tested fine obviously as I did the same with my PR :smile:

**Comment by nicksavov** [comment]
Tested, works well. It fixes the original scenario and when Weblinks 3.4 is installed it tracks the stats. Nice fix, Michael.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6698">issues.joomla.org/joomla-cms/6698</a>.</sub>

File: libraries/cms/component/helper.php [hunk 1]
```diff
@@ -100,6 +100,7 @@ public static function isInstalled($option)
 				->select('COUNT(extension_id)')
 				->from('#__extensions')
 				->where('element = ' . $db->quote($option))
+				->where('type = ' . $db->quote('component'))
 		)->loadResult();
```
Comment (alikon) [inline libraries/cms/component/helper.php]: i was wondering if error condition going uncaught here as per #6591 ?

Comment (mbabker) [inline libraries/cms/component/helper.php]: I think this is one where it would be better for the caller to catch the exception rather than the API method handle it.  The caller could decide if they can proceed with a failed check on if the extension is installed via this query, whereas if we handled it here then the only option would be to `return 0;` which given the implementation would imply the extension isn't installed.
