### PR TITLE
[6.1] Fix none/codemirror editor width and height

### LINKED ISSUE #47292: [6.1] Mail Templates Regression
### What happened?

1. In mail templates set it to use both html and plain text 
2. Open any mail template for editing

### Version

6.1

### Expected result

In 6.0 the two editor areas (html and plain) are displayed full width

Image

### Actual result

In 6.1 Beta the two editors are NOT diaplayed full width

Image

### System Information

_No response_

### Additional Comments

Image

_No response_

### PR DESCRIPTION
**Pull request by RickR2H**
Pull Request resolves #47292 .

This fixes a width and height bug introduced in PR #46438 when there is no editor loaded or editor is set to CodeMirror .

### Summary of Changes
PR #46438 fixed the width and height parameters for TinyMCE. The issue now is that when no editor (editor set to 'none') or CodeMirror is used, the editor collapses because no default width or height is provided.

This occurs, for example, when editing email templates.

### Testing Instructions
Testing instructions are in the original PR #46438.

### Additional Testing Instructions
1. Go to System → Mail Templates. In the Options (top right of the screen), set Mail Format to Both.
2. Open a mail template and check whether the first editor field (where no editor is set) is full width and has a reasonable working height. Also check whether the TinyMCE editor below respects the width and height settings configured in the TinyMCE plugin.
3. In addition to modifying the modules/mod_custom/mod_custom.xml file, add the code below to the XML after the background image field to have all editor options set in the XML file.
```
<field
	name="editor1"
	type="editor"
	label="Editor set to CodeMirror"
	height="600"
	width="600"
	editor="codemirror"
/>
<field
	name="editor2"
	type="editor"
	label="Editor set to None"
	height="300"
	width="800"
	editor="none"
/>
<field
	name="editor3"
	type="editor"
	label="Editor set to TinyMCE"
	height="900"
	width="800"
	editor="tinymce"
/>
<field
	name="editor4"
	type="editor"
	label="Use default editor"
/>
```
4. Switch the default editor in the configuration to TinyMCE, CodeMirror or None, and check if all editor fields are working accordingly in all places in the site.
5. Check if the editor is respecting the TinyMCE plugin settings in the frontend of the site.

### NOTE:
When upgrading from a previous installation, the editor width and height may still be set to the old default of 750px, which can cause the editor to appear too small. With PR #47326, the default editor dimensions are updated to width 100% and height 550px to ensure the editor displays at the correct size after the upgrade.
When testing this PR make sure to set the width to 100% and the height to 550px in the TinyMCE plugin.

### Actual result BEFORE applying this Pull Request
The 'None' editor and CodeMirror editor is collapsed.

### Expected result AFTER applying this Pull Request
The 'None' editor and CodeMirror editor is full width and has a usable working height.

### Link to documentations
Please select:
- [ ] Documentation link for guide.joomla.org: <link>
- [ ] No documentation changes for guide.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

File: libraries/src/Form/Field/EditorField.php [hunk 1]
```diff
@@ -205,8 +205,24 @@ public function setup(\SimpleXMLElement $element, $value, $group = null)
...
+            // Get the configured editor attributes
+            $globalEditor = Factory::getApplication()->get('editor');
+            $editorAttr   = (string) $this->element['editor'] ? (string) $this->element['editor'] : '';
+
+            // Set default values for editor width & height based on editor type
+            // TinyMCE uses plugin settings for sizing, while other editors need explicit dimensions
+            if (
+                $globalEditor === 'tinymce' &&
+                $editorAttr !== 'none' &&
+                $editorAttr !== 'codemirror'
```
Comment (brianteeman) [inline libraries/src/Form/Field/EditorField.php]: and if you are using a different editor?

Comment (RickR2H) [reply libraries/src/Form/Field/EditorField.php]: Then is will fallback to default in the else statement (100% width, 500px height).

File: plugins/editors/codemirror/layouts/editors/codemirror/codemirror.php [hunk 2]
```diff
@@ -31,16 +31,17 @@
...
-if ($options->height) {
-    $style .= 'height:' . $options->height . ';';
+
+if (empty($options->height)) {
+    $options->height = '500px';
 }
 
+$option = ' options="' . $this->escape(json_encode($options)) . '"';
+$style  = 'width:' . $options->width . ';height:' . $options->height . ';';
+
```
Comment (Fedik) [inline plugins/editors/codemirror/layouts/editors/codemirror/codemirror.php:43]: Please move all this from the layout to the CodeMirrorProvider.php 
https://github.com/joomla/joomla-cms/blob/7706b3d95ef0815ec829c8ddc0abfa221af328aa/plugins/editors/codemirror/src/Provider/CodeMirrorProvider.php#L93-L92

In result it will be the same as you made for `EditorNoneProvider.php`

Comment (RickR2H) [reply plugins/editors/codemirror/layouts/editors/codemirror/codemirror.php:43]: Done

File: plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php [hunk 3]
```diff
@@ -76,6 +76,11 @@ public function display(string $name, string $content = '', array $attributes =
         $externalPlugins = [];
         $theme           = 'silver';
 
+        // Reset the old default 750px width of the editor to 100%
+        if (!$width || $width === '750px' || $width === '750') {
```
Comment (brianteeman) [inline plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php]: does this mean that someone can never explicitly set the with to 750?

**Comment by brianteeman** [comment]
FYI the same problem can be seen when editing content in the front end

image

File: plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php (hunk 3 above)
Comment (Fedik) [reply plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php]: Yes, but that was not possible before also, with plugin parameters

Comment (richard67) [inline plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php]: This should become obsolete if PR #47326 gets accepted.

Comment (RickR2H) [reply plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php]: Removed the obsolete code.
