### PR TITLE
Fix Language parsing when parse_ini_file disabled

### LINKED ISSUE #15587: Language Files: Problem after update to 3.7
**My Action**: I did the update using the classic "Joomla Update" page.
**Version**: from 3.6.5 to 3.7
**Installation method**: writes files directly.

**Problem**
After update, the translation of the language fails, i see only the codes instead of the translation.
In fact i see the (ugly) string/code used by JText, e.g.: MOD_MENU_SYSTEM, JSTATUS rtc

### PR DESCRIPTION
**Pull request by PhilETaylor**
closes #15587

Use sensible code to process ini files when moronic web hosts disable parse_ini_file in php.ini

Please test

### CODE REVIEW

**Comment by dgt41** [comment]
@PhilETaylor shouldn't this be conditional, if php_ini_parse not exist then use FOF?

**Comment by PhilETaylor** [comment]
FOF does that check! 

https://github.com/joomla/joomla-cms/blob/91749f845dcf20e097801ecd75da8e4665075a18/libraries/fof/utils/ini/parser.php#L28

**Comment by PhilETaylor** [comment]
I know Travis is unhappy, will look at that in a moment, but this fix fixes the brokenness

**Comment by dgt41** [comment]
Still, this will be faster (one less file, less memory for the good hosts):
```php
		$isMoronHostFile = !function_exists('parse_ini_file');

		if ($isMoronHostFile)
		{
         		$strings = FOFUtilsIniParser::parse_ini_file($filename, true);
		}
		else
		{
			$strings = @parse_ini_file($filename);
		}
```

**Comment by zero-24** [comment]
Should we really create another dependencey to FOF where we try to remove it at other places?

**Comment by PhilETaylor** [comment]
Unless you want to write your own pure PHP implementation of parse_ini_file quickly to resolve the issue... 

FOFUtilsIniParser is nothing but a wrapper to parse_ini_file_php

There is no point in pulling parse_ini_file_php out into another file, and duplicating code in the core...

**Comment by PhilETaylor** [comment]
Actually, this is the only place we do a parse_ini_file anyway, let me rework it then...

File: libraries/joomla/language/language.php [hunk 1]
```diff
@@ -830,7 +830,14 @@ protected function parse($filename)
 			ini_set('track_errors', true);
 		}
 
-		$strings = @parse_ini_file($filename);
+		if (!function_exists('parse_ini_file'))
+		{
+			return FOFUtilsIniParser::parse_ini_file_php($filename, true);
```
Comment (csthomas) [inline libraries/joomla/language/language.php]: Why we can not use the old way before #13407?
```php
return @parse_ini_string(file_get_contents($filename));
```

Comment (PhilETaylor) [reply libraries/joomla/language/language.php]: No idea - I'm assuming that there was a valid reason that they stopped using parse_ini_string ...

**Comment by Bakual** [comment]
Using FOF certainly isn't right.

File: libraries/joomla/language/language.php (hunk 1 above)
Comment (zero-24) [inline libraries/joomla/language/language.php]: As long as we restore:

```
	$contents = file_get_contents($filename);
	$contents = str_replace('_QQ_', '"\""', $contents);
	$strings = @parse_ini_string($contents);
```

That should do the trick.

Maybe add the is_array check too.

**Comment by PhilETaylor** [comment]
Well it works. If someone cares to lay out exactly what "fix" they would prefer to merge, it can be coded... 

I was not involved with the breaking change, I was just fed up with 60+ comments of people saying "it doesnt work" in #15587 so I looked, and within seconds found a solution... 

How you want that solution cemented into the core, well it appears anyway but the ways I chose..

File: libraries/joomla/language/language.php (hunk 1 above)
Comment (PhilETaylor) [reply libraries/joomla/language/language.php]: but that reverts the whole point of #13407 right?

Comment (csthomas) [inline libraries/joomla/language/language.php]: IMO the idea was improve performance. Please replace above line as I suggested.

Comment (zero-24) [inline libraries/joomla/language/language.php]: No just as fallback when the new code don't work for b/c?

Comment (csthomas) [inline libraries/joomla/language/language.php]: This `$contents = str_replace('_QQ_', '"\""', $contents);` is not needed. I tested on php7.0

Comment (PhilETaylor) [reply libraries/joomla/language/language.php]: PR Code updated

**Comment by zero-24** [comment]
@PhilETaylor 

> remove QQ replacement (apparently its not needed)

why do you think so?

parse_ini_file can do that: http://php.net/manual/en/function.parse-ini-file.php

> Constants may also be parsed in the ini file so if you define a constant as an ini value before running parse_ini_file(), it will be integrated into the results. 

But i can not find something like that for parse_ini_string: http://php.net/manual/en/function.parse-ini-string.php

I have not tested this yet but maybe you have..

**Comment by PhilETaylor** [comment]
> why do you think so?

Cause "he said so" :-) https://github.com/joomla/joomla-cms/pull/15620#discussion_r113680858

I can put it back?

File: libraries/joomla/language/language.php (hunk 1 above)
Comment (Bakual) [inline libraries/joomla/language/language.php]: Obviously just using `parse_ini_file` is simpler than using `parse_ini_string` and `file_get_contents`. That's probably the main reason it has been changed.
And as you can read in that PR, there is some automatic handling of _QQ_

**Comment by zero-24** [comment]
As i have said i have not checked it yet and i have not saw that comment above. Needs to be tested.

**Comment by Bakual** [comment]
Honestly, just revert #13407.

**Comment by PhilETaylor** [comment]
I think pretty much that is where I have got to :)

**Comment by zero-24** [comment]
@Bakual i think the rest (array + renaming a var) can stay from that PR? Just that str_replace needs to be checked i guess.

**Comment by PhilETaylor** [comment]
@mbabker

**Comment by PhilETaylor** [comment]
if we are removing the requirement for Joomla to have parse_ini_file enabled, then we can remove this check too ? https://github.com/joomla/joomla-cms/pull/15619/files

**Comment by brianteeman** [comment]
You absolutely can not remove the qq processing!!

**Comment by mbabker** [comment]
Do not revert #13407

The only thing you need to do is basically `if parse_ini_file is usable then use it otherwise use our old way which supports broken INI files`

1) We need to stop allowing broken crap to work in our core APIs
2) The simplest option is to use the simplest function if available, since apparently hosts are 3 steps past moronic we can have a sensible fallback (i.e. the old code which has been proven to work with broken files)
3) The fact that this project is still so reluctant to accept valid third party solutions is really getting out of hand.  We don't have the developers to write everything ourselves because we keep chasing everyone with half an ounce of skill away.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on dc00875cdbaa4f13e66a6443c3ef646457a7f731<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15620">issues.joomla.org/tracker/joomla-cms/15620</a>.</sub>

**Comment by infograf768** [comment]
For testers:
add 
`disable_functions = parse_ini_file`
on your php.ini file
Stop and restart server.

**Comment by PhilETaylor** [comment]
> Stop and restart server.

Or your php-fpm process, depending on how you are running PHP :)

**Comment by csthomas** [comment]
Constants for `parse_ini_string()` are supported in php version 5.3.2.
I have checked it at https://3v4l.org/#preview

Constants are not supported in hhvm 3.19.1 and lower at all for both (`parse_ini_file`, `parse_ini_string`)

I tested with code:
```php
echo phpversion() . "\n";
define('__QQ__', " WORKS ");
print_r(parse_ini_string('A="IT"__QQ__"GREATE!"'));
print_r(parse_ini_file(__DIR__ . '/test.ini'));
```

For hhvm I got:
```
5.6.99-hhvm
Array
(
    [A] => IT__QQ__GREATE!
)
Array
(
    [A] => IT__QQ__GREATE!
)
```

**Comment by PhilETaylor** [comment]
Does Joomla officially support HHVM ? (https://downloads.joomla.org/technical-requirements)

**Comment by csthomas** [comment]
If you will add unittest for `__QQ__` then you will have to:)

**Comment by Bakual** [comment]
Afaik currently unit tests run on HHVM. But the CMS itself not necessary. To my knowledge we don't support it yet officially.

File: tests/unit/suites/libraries/joomla/language/JLanguageTest.php [hunk 2]
```diff
@@ -774,7 +774,11 @@ public function testParse()
 			'Line: ' . __LINE__ . ' test that the strings were parsed correctly.'
 		);
 
-		$strings = $this->inspector->parse(__DIR__ . '/data/bad.ini');
+		/**
+		 * suppressor used as we know this will generate a warning message
+		 * syntax error, unexpected BOOL_TRUE in
```
Comment (wilsonge) [inline tests/unit/suites/libraries/joomla/language/JLanguageTest.php]: in.........

**Review by wilsonge — CHANGES_REQUESTED** [review]

File: tests/unit/suites/libraries/joomla/language/JLanguageTest.php (hunk 2 above)
Comment (PhilETaylor) [reply tests/unit/suites/libraries/joomla/language/JLanguageTest.php:779]: in....  whatever file and whatever path you are running the unit testing suite on, the path is different in travis/my machine but basically its because bad.ini has bad ini data in it... which is expected...

Comment (csthomas) [inline tests/unit/suites/libraries/joomla/language/JLanguageTest.php]: Coluld this https://github.com/PhilETaylor/joomla-cms/pull/1 can be useful?

Comment (mbabker) [inline tests/unit/suites/libraries/joomla/language/JLanguageTest.php]: TBH, I don't think it's even worth the effort to support HHVM anymore.  Seems it is losing traction with the PHP community and big players are dropping support for it because apparently it doesn't have feature parity with PHP core starting with 5.6.

Comment (csthomas) [inline tests/unit/suites/libraries/joomla/language/JLanguageTest.php]: I do not care about support HVVM but I want to force unittest for `_QQ_`.

Comment (csthomas) [inline tests/unit/suites/libraries/joomla/language/JLanguageTest.php]: @mbabker About my proposed changes. Would it be better to remove lines with hhvm support and allow the unit test on hhvm to fail? Or better way is to not add a unit test for `_QQ_` now?

**Comment by rdeutz** [comment]
Can some test this so that we can get this in 3.7.1?

File: libraries/joomla/language/language.php [hunk 3]
```diff
@@ -830,7 +830,21 @@ protected function parse($filename)
...
+			$strings = @parse_ini_string($contents);
+		}
+		else
+		{
+			$strings = @parse_ini_file($filename);
+		}
+
+		if (!is_array($strings))
+		{
+			$strings = array();
```
Comment (csthomas) [inline libraries/joomla/language/language.php]: @PhilETaylor If you are not convinced about merge my PR can you at least remove a ternary operator from line 857:
```php
return is_array($strings) ? $strings : array();
```

 which is equal to your new code:
```php
if (!is_array($strings))
{
	$strings = array();
}
```

Comment (PhilETaylor) [reply libraries/joomla/language/language.php:846]: Done.

File: tests/unit/suites/libraries/joomla/language/JLanguageTest.php (hunk 2 above)
Comment (PhilETaylor) [reply tests/unit/suites/libraries/joomla/language/JLanguageTest.php:779]: @wilsonge Can you close your review please ;-)

Comment (PhilETaylor) [reply tests/unit/suites/libraries/joomla/language/JLanguageTest.php:779]: @csthomas Feel free to propose a PR against joomla-cms/staging with your new unit tests for HHVM

File: libraries/joomla/language/language.php (hunk 3 above)
Comment (csthomas) [inline libraries/joomla/language/language.php]: Thanks

**Comment by PhilETaylor** [comment]
> Can some test this so that we can get this in 3.7.1?

Please everyone test.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 30e69b3a5fddffb36ebc68d427a3c90c522a1d33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15620">issues.joomla.org/tracker/joomla-cms/15620</a>.</sub>

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 30e69b3a5fddffb36ebc68d427a3c90c522a1d33<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15620">issues.joomla.org/tracker/joomla-cms/15620</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by MixingOnBeat** [comment]
Boy, did I also have a rough time with this update from 3.6.5 to 3.7.0.  After the upgrade all the text in the admin panel as well as some text on the public pages were a mess.  I also have a host/server that doesn't allow me to alter php.ini files. :(

I had to revert back my changes (glad I made a backup of the files/database).  I hope you guys find a common ground for 3.7.1.  I read all arguments and though it would be nice that some hosts would not do this, but as long this can be fixed using a bit of code, perhaps this is best for everyone.

**Comment by wilsonge** [comment]
This patch got merged and we hope that 3.7.1 will drop towards the end of next week with the fix for you in :)

**Comment by hakanara** [comment]
Hi all, this issue is still existing with a fresh 3.7.2 installation. Shall I open a new issue?

**Comment by brianteeman** [comment]
Yes please

**Comment by hakanara** [comment]
Fresh installation or a 3.7.3 upgrade still shows us that moronic hosting issue interferes Joomla and prevents Joomla from rocking. All Joomla loverz, let's unite and let Joomla rock!

**Comment by hakanara** [comment]
You are all invited to the reopening of #17198
