### PR TITLE
[5.4] Add publishing checks to banner item retrieval

### LINKED ISSUE #46880: Prevent click counting for inactive banners in com_banners
### Steps to reproduce the issue

1. Create a banner in com_banners and ensure it is linked to a module or category.
3. Note the banner ID (e.g., 42).
5. Set the banner status to "Unpublished" or set a "Finish Publishing" date in the past.
7. Manually trigger a click by calling the click-routing URL: index.php?option=com_banners&task=click&id=42.
9. Check the database table #__banners or the statistics table.

### Expected result
The click should not be counted because the banner is inactive. The click() method in the model should verify if the banner is currently published and within its publishing date range before incrementing the counter.

### Actual result
The clicks counter is incremented regardless of the banner's state or publishing dates. The current implementation of BannerModel::getItem() performs an unconditional update:
`$query->select(
                    [
                        $db->quoteName('a.clickurl'),
                        $db->quoteName('a.cid'),
                        $db->quoteName('a.track_clicks'),
                        $db->quoteName('cl.track_clicks', 'client_track_clicks'),
                    ]
                )
                    ->from($db->quoteName('#__banners', 'a'))
                    ->join('LEFT', $db->quoteName('#__banner_clients', 'cl'), $db->quoteName('cl.id') . ' = ' . $db->quoteName('a.cid'))
                    ->where($db->quoteName('a.id') . ' = :id')
//state, publish_up, publish_down CHECK MISSING
                    ->bind(':id', $id, ParameterType::INTEGER);
    // ... missing state and date checks`

### System information (as much as possible)

Joomla! Version: 5.x (and likely 6.x)
Component: com_banners
Affected File: components/com_banners/src/Model/BannerModel.php

### Additional comments
The display of banners (Impressions) correctly respects the state, publish_up, and publish_down fields. However, the click-tracking task is decoupled from these checks.
I am willing to provide a Pull Request that adds a .where($db->quoteName('state') . ' = 1') and potentially date checks to the update query to ensure data integrity in banner statistics.

### PR DESCRIPTION
**Pull request by nielsnuebel**
Pull Request resolves #46880
### Summary of Changes
This PR enhances the getItem method in com_banners to include state and publishing date validation. By adding these conditions to the database query, we ensure that banner data (including the click URL) is only retrieved if the banner is currently active.

### Technical Changes:

Added $nowDate using Factory::getDate()->toSql() for precise timing.

Extended the WHERE clause to check for state = 1.

Added logic to respect publish_up and publish_down fields (including NULL checks).

### Testing Instructions

1. Identify a banner ID that is currently unpublished or expired.
2. Attempt to trigger a click via the standard routing: index.php?option=com_banners&task=click&id=[ID].
3. Before PR: The system still retrieves the banner object and increments the click counter.
4. After PR: The getItem method returns no result for inactive banners, effectively preventing the click-tracking task from executing.
5. Verify that published banners within their date range continue to track clicks correctly.

### Actual result BEFORE applying this Pull Request
The getItem method retrieves banner details regardless of the publication status, allowing the click-tracking logic to increment counters for inactive ads. This results in "ghost clicks" visible in reporting tools like Looker Studio, where clicks are recorded despite 0 impressions.

### Expected result AFTER applying this Pull Request
Banner data is only returned if the banner is published and within the valid date range. Inactive banners will no longer have their clicks tracked.

### Link to documentations
 - [x] No documentation changes for guide.joomla.org needed
 - [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by nielsnuebel** [comment]
> How can inactive banners get cklicks?

The primary issue is automated traffic from bots or crawlers (like Google or specialized bots) that still have old click-URLs in their index. Here is an example from my server logs:

`13/Feb/2026:00:12:03 +0100] "GET /component/banners/click/288 HTTP/1.1" 404 5527 "-" "Mozilla/5.0 (compatible; FleebsBot/1~w; +https://fleebs.com/bot)" www.domain.tld`

## Why this fix is necessary:

Data Integrity: Currently, Joomla counts these as valid clicks if the ID exists, even if the banner is unpublished or expired. This leads to "ghost clicks" that skew reporting data.

Correct Response: With my fix, the system correctly validates the state and publishing dates within the getItem method. As seen in the log, the server now appropriately returns a 404 instead of processing an invalid interaction.

Returning a 404 is the correct technical response for a resource that is no longer "active" for the public, ensuring clean statistics and better resource management.

File: components/com_banners/src/Model/BannerModel.php [hunk 1]
```diff
@@ -184,7 +185,25 @@ public function &getItem()
                     ->from($db->quoteName('#__banners', 'a'))
                     ->join('LEFT', $db->quoteName('#__banner_clients', 'cl'), $db->quoteName('cl.id') . ' = ' . $db->quoteName('a.cid'))
                     ->where($db->quoteName('a.id') . ' = :id')
-                    ->bind(':id', $id, ParameterType::INTEGER);
+                    ->where($db->quoteName('a.state') . ' = 1')
+                    ->extendWhere(
+                        'AND',
+                        [
+                            $db->quoteName('a.publish_up') . ' IS NULL',
+                            $db->quoteName('a.publish_up') . ' <= :nowDate1',
```
Comment (HLeithner) [inline components/com_banners/src/Model/BannerModel.php]:
```suggestion
                            $db->quoteName('a.publish_up') . ' <= :nowDate',
```

File: components/com_banners/src/Model/BannerModel.php [hunk 2]
```diff
@@ -184,7 +185,25 @@ public function &getItem()
...
+                        ],
+                        'OR'
+                    )
+                    ->extendWhere(
+                        'AND',
+                        [
+                            $db->quoteName('a.publish_down') . ' IS NULL',
+                            $db->quoteName('a.publish_down') . ' >= :nowDate2',
```
Comment (HLeithner) [inline components/com_banners/src/Model/BannerModel.php]:
```suggestion
                            $db->quoteName('a.publish_down') . ' >= :nowDate',
```

File: components/com_banners/src/Model/BannerModel.php [hunk 3]
```diff
@@ -184,7 +185,25 @@ public function &getItem()
...
+                        ],
+                        'OR'
+                    )
+                    ->bind(':id', $id, ParameterType::INTEGER)
+                    ->bind([':nowDate1', ':nowDate2'], $nowDate);
```
Comment (HLeithner) [inline components/com_banners/src/Model/BannerModel.php]:
```suggestion
                    ->bind(':nowDate', $nowDate);
```

**Review by HLeithner — DISMISSED** [review]
You don't need to provide the same parameter twice.

File: components/com_banners/src/Model/BannerModel.php (hunk 1 above)
Comment (nielsnuebel) [reply components/com_banners/src/Model/BannerModel.php]: i will use :publishUp

File: components/com_banners/src/Model/BannerModel.php (hunk 2 above)
Comment (nielsnuebel) [reply components/com_banners/src/Model/BannerModel.php]: i will use :publishDown

File: components/com_banners/src/Model/BannerModel.php (hunk 3 above)
Comment (nielsnuebel) [reply components/com_banners/src/Model/BannerModel.php]: perfect

File: components/com_banners/src/Model/BannerModel.php [hunk 4]
```diff
@@ -171,6 +171,7 @@ public function &getItem()
             $db = $this->getDatabase();
 
             $loader = function ($id) use ($db) {
+                $nowDate = Factory::getDate()->toSql();
                 $query = $db->getQuery(true);
```
Comment (tecpromotion) [inline components/com_banners/src/Model/BannerModel.php]:
```suggestion
                $query   = $db->getQuery(true);
```

fix cs

**Review by tecpromotion — CHANGES_REQUESTED** [review]
see https://github.com/joomla/joomla-cms/actions/runs/21989191781/job/63531371242?pr=46881

**Review by tecpromotion — APPROVED** [review]

**Comment by beni71** [comment]
I have tested this item :white_check_mark: successfully on 0fd57ffe446e550deb13d6e3b82c40a556d451c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/46881">issues.joomla.org/tracker/joomla-cms/46881</a>.</sub>
