### PR TITLE
Front end menu items translated in error

### LINKED ISSUE #19800: Weirdest ever bug in Joomla: menu voice "Sun" become "Dom"
### Steps to reproduce the issue
Create a menu voice with title "Sun", save and close.

### Expected result
In the menu i must see (image edited to reproduce expected result)
image

### Actual result
:scream: :scream: :scream:
image

**Sun** becomes **Dom** ... WHY?

### System information (as much as possible)
Versione di Joomla! | Joomla! 3.8.5 Stable [ Amani ] 6-February-2018 15:00 GMT
-- | --
Versione piattaforma Joomla! | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

### Additional comments

I have tested this on 10 joomla websites, with php 5.6.x and 7.x, the result is the same!
Tested on Chrome, Firefox, Edge.

**Is "sun" a magic word???**

If you write "sun" or "Sun" or "SUN" the result is the same. If i write "Sun " (with a space at the end) i can see "Sun" in menu voice.

It's so weird!

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request to fix #19800

PR #13606 introduced translatable admin menu item creation but the code didnt check if the menu item was for the frontend or the admin before doing the translation

### Test Instructions
1. Install any additional language eg italian
2. Create a menu item called "Sun"
3. On the list of all the menu items you will see it is displayed as "Dom" - the italian translation
4. Enable language debug
5. On the list of all the menu items you will see all your menu item titles are surrounded by ?? - to indicate no translation found -  except for "Dom" which has ** instead to show it has been translated
6. Apply this PR
7. Sun still says Sun
8. There are NO ?? or ** when in language debug mode
9. Bonus - check a custom admin menu item and you will see it can be translated

### CODE REVIEW

File: administrator/components/com_menus/models/items.php [hunk 1]
```diff
@@ -531,7 +532,10 @@ public function getItems()
 					}
 
 					// Translate component name
+					if ($client === 1)
+					{
```
Comment (Quy) [inline administrator/components/com_menus/models/items.php]: Remove trailing tabs on lines 536 & 538. Indent line 537

File: administrator/components/com_menus/models/items.php [hunk 2]
```diff
@@ -531,7 +532,10 @@ public function getItems()
 					}
 
 					// Translate component name
-					$item->title = JText::_($item->title);
+					if ($client === 1)
+					{
+						$item->title = JText::_($item->title);
+					}
```
Comment (Quy) [inline administrator/components/com_menus/models/items.php]: Remove trailing tabs.

**Comment by simbus82** [comment]
I have tested this item :white_check_mark: successfully on c4b967f90f31a2a633c3543f8f8b53a530c62f25<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19802">issues.joomla.org/tracker/joomla-cms/19802</a>.</sub>

image

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c4b967f90f31a2a633c3543f8f8b53a530c62f25<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19802">issues.joomla.org/tracker/joomla-cms/19802</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19802">issues.joomla.org/tracker/joomla-cms/19802</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by infograf768** [comment]
@izharaazmi 
As you were the one who introduced this, would be good to see your comment.
I believe personally that this PR is correct.

**Comment by izharaazmi** [comment]
This PR solves the issue in question. 

---

**Additional comments beyond the scope of this PR**

However, this is one of the heuristic approaches used in our core. I'd suggest having a flag `translate_title` in the menu item params to indicate whether it should be translated or not. Because not all the Admin Menu are required to be translated, some may be hardcoded text.

Another bonus I can see (though I have not given enough thought to this) that this will allow translation of frontend menu items as well if and when desired.

**Comment by infograf768** [comment]
> Another bonus I can see (though I have not given enough thought to this) that this will allow translation of frontend menu items as well if and when desired.

Indeed, but it may have unwanted results as the original issue here demonstrates, i.e. when there is already a string constant which fits the title or alias.

**Comment by izharaazmi** [comment]
Yes, alias would be a matter of concern in case of frontend.
