### PR TITLE
[5.2] EmailRule unique should look at submitted input data instead of stored form data.

### LINKED ISSUE #43821: [5.1] EmailRule unique should look at input instead of form.
### Steps to reproduce the issue

Kind of hard to explain. I am making a 3-party component that using the EmailRule to check for unique="true".

On save it will always fail with "Exception has occurred. UnexpectedValueException: The email address you entered is already in use. Please enter another email address." 

The issue is that in the FormController in the save function we are not loading the form data. So when we get to the validation, the form data is always empty but the EmailRule is checking for form data to validate uniqueness.

The fix for it is to change:

https://github.com/joomla/joomla-cms/blob/183985b4a7b9adf8d20b29964e11994cef5a226f/libraries/src/Form/Rule/EmailRule.php#L167

to

```
$userId = (int) $input->get('id', 0); 
```

This will check the submitted data instead of the form load data.

### Expected result

Be able to validate unique email

### Actual result

Exception has occurred. 
UnexpectedValueException: The email address you entered is already in use. Please enter another email address.

### System information (as much as possible)

dbserver: mysql
dbversion: 8.0.21-12.1
phpversion: 8.3.8
server: nginx/1.25.4
version: Joomla! 5.1.1 Stable [ Kudumisha ] 28-May-2024 16:00 GMT

### PR DESCRIPTION
**Pull request by Flowman**
Pull Request for Issue #43821.

### Summary of Changes

Fix that validation is looking for submitted input data instead of stored form data.

### Testing Instructions

Code review

or

follow instructions #43821

### CODE REVIEW

File: libraries/src/Form/Rule/EmailRule.php [hunk 1]
```diff
@@ -164,7 +164,7 @@ public function test(\SimpleXMLElement $element, $value, $group = null, Registry
             $query = $db->getQuery(true);
 
             // Get the extra field check attribute.
-            $userId = ($form instanceof Form) ? (int) $form->getValue('id') : 0;
+            $userId = ($input instanceof Registry) ? $input->get('id') : 0;
```
Comment (bembelimen) [inline libraries/src/Form/Rule/EmailRule.php]: Hey @Flowman I see what you're doing here. I'm not sure if your solution is THE solution, because it raises some issues like when someone is using the [onContentBeforeValidateData](https://github.com/joomla/joomla-cms/blob/5.1-dev/libraries/src/MVC/Model/FormModel.php#L213-L216) trigger via plugin, data changes are not reflected with your fix.

Beside that (independent from your PR) it feels wrong to assume, that the "id" is always the ```userId``` so probably a fix would be to make this flexible?

Comment (peter1szalatnay) [reply libraries/src/Form/Rule/EmailRule.php]: I can do that it check both form and input values. 

But the id must be the user id as it check in the user table for unique id. What else should it using? Don't think I can change the query to be more dynamic.

**Comment by degobbis** [comment]
I have tested this item :white_check_mark: successfully on 16b59a2aefeae836054399d94fa3009f744ac69f<br /><br />Makes sense<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43822">issues.joomla.org/tracker/joomla-cms/43822</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.2-dev.

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 16b59a2aefeae836054399d94fa3009f744ac69f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43822">issues.joomla.org/tracker/joomla-cms/43822</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43822">issues.joomla.org/tracker/joomla-cms/43822</a>.</sub>

**Comment by Hackwar** [comment]
Thank you for your contribution!
