### PR TITLE
[4] Ensure template logo has relative links regardless of SEF Settings

### LINKED ISSUE #31989: [4b6] Disable SEF Plugin breaks default template logo url
### Steps to reproduce the issue

Joomla 4 beta 6 - install the "Testing Sample Data"
Visit frontend, click a menu link in the left menu to get to an article
Note that the CASSIOPEIA logo (white text on blue background) is present

In Joomla Admin disable the "System - SEF" plugin

Refresh your article page on the frontend

Note the logo is now a broken image

### Expected result

Regardless of SEF settings expectation is to see the logo

Screenshot 2021-01-10 at 17 42 09

Image logo url is http://127.0.0.1:4444/templates/cassiopeia/images/logo.svg

### Actual result

Note that `joomal4b6` shown in this screenshot is my "Site name" in Joomla Global Config and is not related to the SEF issue. 

Screenshot 2021-01-10 at 17 43 07

Image logo URL is http://127.0.0.1:4444/index.php/templates/cassiopeia/images/logo.svg

### PR DESCRIPTION
**Pull request by PhilETaylor**
Pull Request for Issue Closes #31989
Replacement PR for https://github.com/joomla/joomla-cms/pull/32714

### Summary of Changes

Prepend templatePath with Uri:root to Ensure templatePath is always absolute and not a broken relative url

### Testing Instructions

See #31989

Visit frontend **, click a menu link in the left menu to get to an article**
Note that the CASSIOPEIA logo (white text on blue background) is present

In Joomla Admin disable the "System - SEF" plugin

Refresh your article page on the frontend

Note the logo is now a broken image

### Actual result BEFORE applying this Pull Request

paths are relative, and therefore image doesn't display when non-SEF mode and not at / (ie. in a sub folder or not on the home page where url contains /index.php/path/to  like http://127.0.0.1:4444/index.php/component/users/reset?Itemid=101)

### Expected result AFTER applying this Pull Request

regardless of SEF plugin status, the image and assets loaded from $templatePath load correctly. 

### Documentation Changes Required

none

### CODE REVIEW

File: templates/cassiopeia/index.php [hunk 1]
```diff
@@ -66,15 +66,15 @@
...
+	$logo = '<img src="' . Uri::root(true) . '/' . htmlspecialchars($this->params->get('logoFile'), ENT_QUOTES) . '" alt="' . $sitename . '">';
 }
 elseif ($this->params->get('siteTitle'))
 {
 	$logo = '<span title="' . $sitename . '">' . htmlspecialchars($this->params->get('siteTitle'), ENT_COMPAT, 'UTF-8') . '</span>';
 }
 else
 {
-	$logo = '<img src="' . $templatePath . '/images/logo.svg" class="logo d-inline-block" alt="' . $sitename . '">';
+	$logo = '<img src="' . Uri::root(true) . '/' . $templatePath . '/images/logo.svg" class="logo d-inline-block" alt="' . $sitename . '">';
```
Comment (dgrammatiko) [inline templates/cassiopeia/index.php]: Actually, there's an API for this:
```php

$logo = HTMLHelper::_('image', 'logo.svg', $sitename, ['class' => 'logo d-inline-block'], true, -1);
```

**Review by dgrammatiko — CHANGES_REQUESTED** [review]

File: templates/cassiopeia/index.php (hunk 1 above)
Comment (joomdonation) [reply templates/cassiopeia/index.php]: @dgrammatiko Do we really need to use API for this? I think the code is fine as it is now. It works and save the system from having to find the logo from multiple places.

Comment (dgrammatiko) [reply templates/cassiopeia/index.php]: No, but it will be easier if we ever want to transition this template to the new mode, child templates

Comment (joomdonation) [reply templates/cassiopeia/index.php]: Hmm, I don't know about child templates yet, so I will leave it to @PhilETaylor for making the suggested change or not.

Comment (dgrammatiko) [reply templates/cassiopeia/index.php]: Also due to reverse order (template wins) I think there are no extra lookups ( although I might be wrong on this one, it’s been some time since I looked at that code)

Comment (joomdonation) [reply templates/cassiopeia/index.php]: I haven't looked carefully enough, too. But since the template wins logic, I see no benefit for making API call and would leave it as how it is now (except something effect child templates logic as you mentioned)

Comment (dgrammatiko) [reply templates/cassiopeia/index.php]: The point is that if we ever convert this to inheritable (eg support child templates) the hardcoded path will be broken, but thus my comment in the first place

**Comment by PhilETaylor** [comment]
Switched to Joomla API with preceding `/` to make it actually work.

File: templates/cassiopeia/index.php [hunk 2]
```diff
@@ -66,15 +66,15 @@
...
+	$logo = '<img src="' . Uri::root(true) . '/' . htmlspecialchars($this->params->get('logoFile'), ENT_QUOTES) . '" alt="' . $sitename . '">';
 }
 elseif ($this->params->get('siteTitle'))
 {
 	$logo = '<span title="' . $sitename . '">' . htmlspecialchars($this->params->get('siteTitle'), ENT_COMPAT, 'UTF-8') . '</span>';
 }
 else
 {
-	$logo = '<img src="' . $templatePath . '/images/logo.svg" class="logo d-inline-block" alt="' . $sitename . '">';
+	$logo = HTMLHelper::_('image', '/' . $templatePath . '/images/logo.svg', $sitename, ['class' => 'logo d-inline-block'], true, -1);
```
Comment (dgrammatiko) [inline templates/cassiopeia/index.php]: This part `'/' . $templatePath . '/images/logo.svg'` should be the same as `'logo.svg'` but for that to work the last argument needs to switch from `-1` to `0`

Comment (PhilETaylor) [reply templates/cassiopeia/index.php]: Done.

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 2898ee997616ab017c81873fc2ac0f338b401096<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32822">issues.joomla.org/tracker/joomla-cms/32822</a>.</sub>

File: templates/cassiopeia/index.php (hunk 2 above)
Comment (dgrammatiko) [reply templates/cassiopeia/index.php]: Thanks

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 2898ee997616ab017c81873fc2ac0f338b401096<br /><br />Tested successfully in Beta8-dev of 24 March in Wampserver 3.2.4 using PHP 8.0.2.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32822">issues.joomla.org/tracker/joomla-cms/32822</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32822">issues.joomla.org/tracker/joomla-cms/32822</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks!
