### PR TITLE
[6.0] Fix sidebar admin flashing icons (alternative to #47268)

### LINKED ISSUE #32273: [4.0] Admin mod_menu no active menu if URL has additional params
### Steps to reproduce the issue
Navigate to `/administrator/index.php?option=com_content&view=articles`. Notice `Content > Articles` is open.
Next, add some dummy parameters: `/administrator/index.php?option=com_content&view=articles&test=1`.
Or even: `/administrator/index.php?option=com_content&view=articles#test`

### Expected result
`Content > Articles` shows open.

### Actual result
Menu is completely closed and no menu item shows active.

### Additional comments
This seems to be caused by `media/mod_menu/js/admin-menu.js`:
```
if (currentUrl === link.href) {
```
Perhaps changing this to:
```
if (currentUrl.indexOf(link.href) === 0) {
```
would work better

### PR DESCRIPTION
**Pull request by LadySolveig**
Pull Request resolves #32273 
Issue found CMS release team testing session on: February 12, 2026 (alternative to #47268).

- [X] I read the [Generative AI policy](https://developer.joomla.org/generative-ai-policy.html) and my contribution is either not created with the help of AI or is compatible with the policy and GNU/GPL 2 or later.

### Summary of Changes

Server-side active path detection to prevent flashing icons in admin menu sidebar with fallbacks for edge cases.

**Menu active state detection and propagation:**
- Added a new `setActivePath` method to mark the active menu path server-side. The existing JS logic was largely transferred 1:1 to the backend method.

**JavaScript integration and fallback logic:**
- Modified `admin-menu.es6.js` to strip server-rendered `mm-show`/`mm-active` classes before initializing MetisMenu, then re-apply them to avoid transition issues and ensure the active state is preserved without visual glitches.
- Added a client-side fallback in `admin-menu.es6.js` to detect and set the active menu item if the server-side logic fails.

### Testing Instructions

1. Open the Joomla backend, expand the Components menu, and select one of the submenu entries.

2. Test other submenu entries to see if the icons are glitching and if everything loads directly without flickering with the fix.

3. Compare if all menu and submenu items are loaded and reachable as before.

4. Install a third party componenent that has menu items in the sidebar in backend. All should be visible and work as before.

5. Additional test that deep nesting also works as expected - introduced in 6.0 see testing instructions here #46550

You need the Firefox browser to test this, as the flickering is no longer noticeable on Chromium-based browsers (see #45787)

> [!IMPORTANT]  
> For this to test an update of the media asset is  required, please use the prebuilt packages or run npm install.

### Actual result BEFORE applying this Pull Request

Glitching icons in the admin menu sidebar when opening a submenu item as the active page 

https://github.com/user-attachments/assets/16f34cd3-2c16-459b-9f68-e8d9956b3a22

### Expected result AFTER applying this Pull Request

https://github.com/user-attachments/assets/f04c8e56-11d3-41ac-a068-7f4200dc2afa

### Link to documentations
Please select:
- [ ] Documentation link for guide.joomla.org: <link>
- [X] No documentation changes for guide.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

File: administrator/modules/mod_menu/src/Menu/CssMenu.php [hunk 1]
```diff
@@ -495,6 +499,61 @@ protected function preprocess($parent)
...
+    /**
+     * Set the active path in the menu tree based on the current URL
+     *
+     * @return  void
+     *
+     * @since   __DEPLOY_VERSION__
+     */
+    protected function setActivePath()
+    {
+        $currentUrl     = Uri::getInstance()->toString();
```
Comment (Fedik) [inline administrator/modules/mod_menu/src/Menu/CssMenu.php:511]: You can get relative URL with:
```php
Uri::getInstance()->toString(['path', 'query', 'fragment']);
```
This will save you a lot of code, than comparing full path.

Comment (Fedik) [reply administrator/modules/mod_menu/src/Menu/CssMenu.php:511]: hm, or maybe not, for installation in subforlder

Comment (LadySolveig) [reply administrator/modules/mod_menu/src/Menu/CssMenu.php:511]: Thanks for taking a look at it. :)

**Comment by brianteeman** [comment]
> Thanks for the video and the specific example. That has made the issue clearer to me. We'll address that in the other PR.
> 

Found the problem shown in the video and its completely unrelated to the menu code but is actually an error in the categories view itself. If you check the example in my video you will see that the url at the end which doesnt have the expanded menu etc is missing the "view=" part of the url. I will document it more tomorrow but just wanted to post a quick note now so you dont try to fix it in the menu tonight
