### PR TITLE
Fix JInputCookie setter to work with arrays (fixes #8073 )

### LINKED ISSUE #8073: Impossible to set cookie value to array
Setter $value parameter in JInputCookie is declared as mixed, so it should accept array values, the same as other setters. But currently JInputCookie set method fails do do this is faulty as it tries to do just setcookie($name, $value) - which does not work for arrays. Cookies with array values need to be set for each array value separately with array keys in name - see example 3 here http://php.net/manual/en/function.setcookie.php

### PR DESCRIPTION
**Pull request by klas**
Fix JInputCookie set method to support array values (fixes #8073 )

---
## Steps to reproduce the issue

Run this code 
JFactory::getApplication()->input->cookie->set("arraytest", array("asssoc1"=>"assoc1value","asssoc2"=>"assoc2value" ),time() + 365 \* 86400);
## Expected result

Cookies arraytest[asssoc1] with value "assoc1value", and arraytest[asssoc2] with value "assoc2value" beeing set
## Actual result

Warning: setcookie() expects parameter 2 to be string, array given in libraries\joomla\input\cookie.php on line 85
No cookie is set

### CODE REVIEW

**Comment by Fedik** [comment]
@klas but you know that the Browser Cookies accept only String? :wink:
I think, if you need something extra, you need to do it in your code

**Comment by klas** [comment]
@Fedik not exactly true, thaere are also array cookies, see example #3 here http://php.net/manual/en/function.setcookie.php

**Comment by infograf768** [comment]
This is B/C in multilanguage.

**Comment by Fedik** [comment]
@klas hm, this I missed sorry :wink:

**Comment by klas** [comment]
@infograf768 After the change method only starts accepting arrays (which did not work at all before, see https://github.com/joomla/joomla-cms/issues/8073 ), but it still accepts strings, so there should be no B/C change (for strings code is exactly the same as it was before).

**Comment by infograf768** [comment]
@klas 
Yep, that's what I confirmed above. :smile:

**Comment by klas** [comment]
Ah, sorry, I thought you are saying it is not B/C :)

File: libraries/joomla/input/cookie.php [hunk 1]
```diff
@@ -82,7 +82,18 @@ public function __construct(array $source = null, array $options = array())
 	 */
 	public function set($name, $value, $expire = 0, $path = '', $domain = '', $secure = false, $httpOnly = false)
 	{
-		setcookie($name, $value, $expire, $path, $domain, $secure, $httpOnly);
+
```
Comment (zero-24) [inline libraries/joomla/input/cookie.php]: Can You remove This line or place a quick comment like '// Handle array value'

Comment (klas) [inline libraries/joomla/input/cookie.php]: Done (removed line)

**Comment by klas** [comment]
@zero-24 I removed the empty line, so it should be ok now

File: libraries/joomla/input/cookie.php (hunk 1 above)
Comment (zero-24) [inline libraries/joomla/input/cookie.php]: :+1:

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 45ef9af9b6af0301a70ce73686f3d1eb7cb6dfdf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8081">issues.joomla.org/joomla-cms/8081</a>.</sub>

**Comment by zero-24** [comment]
Works here see: screen shot 2015-10-20 at 09 15 04<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8081">issues.joomla.org/joomla-cms/8081</a>.</sub>

**Comment by kolvar** [comment]
I have tested this item :white_check_mark: successfully on 45ef9af9b6af0301a70ce73686f3d1eb7cb6dfdf<br /><br />Tested whit given code. Works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8081">issues.joomla.org/joomla-cms/8081</a>.</sub>

**Comment by kolvar** [comment]
I have tested this item :white_check_mark: successfully on 45ef9af9b6af0301a70ce73686f3d1eb7cb6dfdf<br /><br />Tested whit given code. Works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8081">issues.joomla.org/joomla-cms/8081</a>.</sub>

**Comment by SniperSister** [comment]
2 successful tests, setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8081">issues.joomla.org/joomla-cms/8081</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @klas! Merged.
