### PR TITLE
[3.5.0 Beta] Fix permissons editing with the PDO Driver

### LINKED ISSUE #8321: 3.5beta1 - Permission editing is broken
I tried test the beta, and noticed that permission editing does not really work, or works randomly.
After changing any permission dropdown I got undefined error.

**Global configuration:**
After any change I got undefined error and X icon
screen 2015-11-07 15 36 14 1241x383

**Module editing:**
Sometimes it works, sometimes it is not.
screen 2015-11-07 15 37 09 836x433

### PR DESCRIPTION
**Pull request by zero-24**
### What is changed

Not allways we get a boolean if a SQL is true. e.g. on PDO we get a PDO object.
### How to test
- install beta 1 (PDO Database Driver)
- go to the global config.
- try to change the config
- you got an "undefined" error
- apply the patch
- it works.
- try it again with the mysql driver.

Fixes #8321 Thnaks @Fedik

### CODE REVIEW

**Comment by Fedik** [comment]
I can confirm, that this pull fixes part of #8321 issue :wink:

File: administrator/components/com_config/model/application.php [hunk 1]
```diff
@@ -410,13 +410,20 @@ public function storePermissions($array)
...
-
-				return $result;
 			}
 		}
 		catch (Exception $e)
 		{
 			return $e->getMessage();
 		}
+
+		// Not allways we get true on success e.g. PDO but allways false if it fails.
```
Comment (wilsonge) [inline administrator/components/com_config/model/application.php]: `allways` = always (one `l` :smile: )

File: administrator/components/com_config/model/application.php [hunk 2]
```diff
@@ -410,13 +410,20 @@ public function storePermissions($array)
 				$this->db->setQuery($query);
 
 				$result = $this->db->execute();
-
-				return $result;
```
Comment (wilsonge) [inline administrator/components/com_config/model/application.php]: Rather than all of the below I think doing `return (bool) $result` makes the same fix with less code :)

**Comment by wilsonge** [comment]
I've tested this and it works - but I'd much prefer the solution that I've commented in the code - which does the same thing in far less code :)

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 8f311e9cf7543cbe70b99d14001cb7286eb81d17<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8322">issues.joomla.org/joomla-cms/8322</a>.</sub>

**Comment by zero-24** [comment]
Fixed @wilsonge

**Comment by wilsonge** [comment]
I have tested this item :white_check_mark: successfully on 93ff1931547ffd3ea5592a195de9b25e9fbb5c5a<br /><br />Works successfully with PDO and MySQLi drivers<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8322">issues.joomla.org/joomla-cms/8322</a>.</sub>

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 93ff1931547ffd3ea5592a195de9b25e9fbb5c5a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8322">issues.joomla.org/joomla-cms/8322</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8322">issues.joomla.org/joomla-cms/8322</a>.</sub>
