### PR TITLE
Fix inconsistent code in JTable. Fix #6901

### LINKED ISSUE #6901: Possible issues / inconsistent code in JTable
We have several code like this in JTable

````php
if (property_exists($this, 'checked_out') || property_exists($this, 'checked_out_time'))
{
	$query->where('(' . $this->getColumnAlias('checked_out') . ' = 0 OR ' . $this->getColumnAlias('checked_out') . ' = ' . (int) $userId . ')');
	$checkin = true;
}
````

Here is one example https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/table/table.php#L1568-L1572

As you see, we allow developers to set column alias for a column in case they want to use different field name than the one using by Joomla. However, the problem is that in in the check in if command, we hardcode the field name to checked_out and checked_out_time, not using getColumnAlias. So if someone uses column alias, the code won't run properly.

Should we update the code to make it consistent and correct it in case someone uses column alias?

### PR DESCRIPTION
**Pull request by joomdonation**
## PR Summary

Our **JTable** class suppose to allow developers to use column alias for the following common columns: **checked_out**, **checked_out_time**, **hits** (for example, in my custom database table, I can use **view_count** field instead of **hits** and use setColumnAlias to map that field with the original hits field)

However, there are places in the class, the columns name are hardcoded instead of using it's alias (if it is set). That makes the following methods checkIn, checkOut, publish, hit won't work properly if someone uses custom columns name in his database table despite that he set the alias properly.

This PR simply fix that mistakes. I also move the  getColumnAlias out of the for loop in publish method, so it should has litle performance improvement, too
## Testing instructions

I think this PR just need code review from maintainers. The modification will affect check in, checkout, publish methods, so if you want to help testing this change, you can login to backend of your site, create an article, try to publish, checkin, checkout it and make sure everything still works as expected.

### CODE REVIEW

File: libraries/joomla/table/table.php [hunk 1]
```diff
@@ -1073,15 +1076,15 @@ public function checkOut($userId, $pk = null)
...
+			->set($this->_db->quoteName($checkedOutField) . ' = ' . (int) $userId)
+			->set($this->_db->quoteName($checkedOutTimeField) . ' = ' . $this->_db->quote($time));
 		$this->appendPrimaryKeys($query, $pk);
 		$this->_db->setQuery($query);
 		$this->_db->execute();
 
 		// Set table values in the object.
-		$this->checked_out      = (int) $userId;
-		$this->checked_out_time = $time;
+		$this->$checkedOutField      = (int) $userId;
```
Comment (wilsonge) [inline libraries/joomla/table/table.php]: I *think* that PHP 7 requires you to use the syntax $this->{$checkedOutField} and will fatal with the code you have there

Comment (mbabker) [inline libraries/joomla/table/table.php]: No, for that it's fine.  If the code here was something like `$object->{$array['key']}` the brackets would be needed.

**Comment by wilsonge** [comment]
Merged on review
