### PR TITLE
[5.3] Show correct custom fields when creating article after filtering by multiple categories

### LINKED ISSUE #45303: Creating a new article when filtering several categories, shows custom fields for all those categories
### Steps to reproduce the issue
- Create two categories: "Events" and "News"

- Create two custom fields:
"events_title", text; assign it to the Events category;
"news_title", text; assign it to the News category;

- At the article manager, filter by the Events and News category;
- Create a new article
- Go to the fields tab and notice the custom fields there!

### Expected result
Depending on the category that is chosen (when filtering by multiple categories, Joomla chooses one, I don't know what is the criteria), **it should show only the custom fields for that category!**
Let's say Joomla selected "Events" as the category, at the Fields tab, it show only show the "events_title" custom field.

### Actual result
Even though (for example) the "Events" category is chosen, at the Fields tab, **it shows the custom fields for the Events and for the News** (events_title and news_title).

Additionally, if I try to change the category to the other one (ex: if it was "Events", change to "News") it changes nothing (also Joomla's icon doesn't show, indicating that nothing is being loaded).

If I select another category not part of the filtered articles' categories, it reloads the custom fields, and if I change to "Events" it shows the correct (only one) field.

### System information (as much as possible)
Joomla 5.2.5
Apache 2.4.54
MariaDB 8.0.27
PHP 8.2.0

### PR DESCRIPTION
**Pull request by AdarshSantoria**
### Summary of Changes

This PR fixes a bug where creating a new article after filtering by **multiple categories** (e.g. "News" and "Events") incorrectly displays **all custom fields** from all those categories on the "Fields" tab.

Joomla previously used the `catid` filter directly from user state or input, which led to ambiguous behavior when multiple categories were selected. This fix:

- Detects when `category_id` filter is an array
- Selects the **first selected category** from the filtered list
- Ensures only relevant custom fields are loaded for the selected category
- Supports fallback logic for single-category filter or default category

This resolves #45303 and improves clarity and correctness of the custom field rendering in the admin UI.

---

### Testing Instructions

1. Create two categories: **Events** and **News**
2. Create two custom fields:
   - `events_title` → assigned to **Events**
   - `news_title` → assigned to **News**
3. Go to **Content > Articles**
4. Apply **category filter** for both "Events" and "News"
5. Click **New Article**
   - ✅ Only one custom field (`events_title` or `news_title`) should appear on the "Fields" tab
6. Change category using dropdown
   - ✅ Custom fields update correctly

---

### Actual result BEFORE applying this Pull Request

Screenshot (37)
- When filtered by multiple categories and clicking "New", **all fields** from all selected categories are loaded.
- Changing category does **not reload** the field list properly.

---

### Expected result AFTER applying this Pull Request

Screenshot (36)
- Only the **first selected category’s** custom fields are loaded initially
- Changing category in the form **correctly reloads** the associated custom fields dynamically
- Prevents confusion and clutter in the custom fields UI

---

### Link to documentation

Please select:
- [ ] Documentation link for docs.joomla.org:
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org:
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 56c2e62114ff97e61788d58109d0107c8e5bae43<br /><br />Functionality works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/45353">issues.joomla.org/tracker/joomla-cms/45353</a>.</sub>

**Comment by JackJoeJack** [comment]
I also have tested this item ✅ successfully on [56c2e62](https://github.com/joomla/joomla-cms/commit/56c2e62114ff97e61788d58109d0107c8e5bae43)

 Functionality works as described

File: administrator/components/com_content/src/Model/ArticleModel.php [hunk 1]
```diff
@@ -587,7 +587,18 @@ protected function loadFormData()
                         ((isset($filters['published']) && $filters['published'] !== '') ? $filters['published'] : null)
                     )
                 );
-                $data->set('catid', $app->getInput()->getInt('catid', (!empty($filters['category_id']) ? $filters['category_id'] : null)));
+
+                // Fix: If multiple categories are filtered, pick the first one to avoid loading all fields
```
Comment (QuyTon) [inline administrator/components/com_content/src/Model/ArticleModel.php]:
```suggestion
                // If multiple categories are filtered, pick the first one to avoid loading all fields
```

**Comment by richard67** [comment]
I've just double-checked this PR and it works and seems not to break anything else.
