### PR TITLE
Fix #5955: Search Engine Friendly URLs is not friendly to TOS article

### LINKED ISSUE #5955: Search Engine Friendly URLs is not friendly to TOS article
#### Steps to reproduce the issue
1. Enable "User - Profile" plugin and assign an article with TOS.
2. Set "Search Engine Friendly URLs" to "Yes" at global configuration. 

#### Expected result
When user wants create a account and click "Terms of Service:" link, it will show
a modal box with TOS article.

#### Actual result
When user wants create a account and click "Terms of Service:" link, it will show
a modal box with index page (eg. feature articles) not the TOS article.
When "Search Engine Friendly URLs" switch to "No", the modal box shows TOS article as  normal. 

#### System information (as much as possible)
From the system information:
PHP Built On: Linux 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64
Database Version: 5.5.41-0ubuntu0.14.04.1
Database Collation: utf8_general_ci
PHP Version: 5.5.9-1ubuntu4.5
Web Server: Apache/2.4.7 (Ubuntu)
WebServer to PHP Interface: apache2handler
Joomla! Version: Joomla! 3.4.0-beta1 Beta [ Ember ] 27-January-2015 20:00 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5

#### Additional comments
the issue was also on Joomla! 3.3.6.

### PR DESCRIPTION
**Pull request by joomdonation**
Please see https://github.com/joomla/joomla-cms/issues/5955 to understand the issue. 

To test this PR:
1. Enable "User - Profile" plugin and assign an article with TOS
2. Set "Search Engine Friendly URLs" to "Yes" at global configuration
3. Check and make sure When user wants create a account and click "Terms of Service:" link, it will show
   a modal box with TOS article.

### CODE REVIEW

File: plugins/user/profile/fields/tos.php [hunk 1]
```diff
@@ -71,25 +71,30 @@ protected function getLabel()
...
-				ENT_COMPAT, 'UTF-8'
-			) . '"';
+					trim($text, ':') . '<br />' . ($this->translateDescription ? JText::_($this->description) : $this->description),
+					ENT_COMPAT, 'UTF-8'
+				) . '"';
 		}
 
 		$tosarticle = $this->element['article'] > 0 ? (int) $this->element['article'] : 0;
 
-		$link = '';
```
Comment (zero-24) [inline plugins/user/profile/fields/tos.php]: @joomdonation are you sure by removing this line?

How we handle it (`$link`) if no  `$tosarticle` is set?

File: plugins/user/profile/fields/tos.php [hunk 2]
```diff
@@ -71,25 +71,30 @@ protected function getLabel()
...
+
+			$db    = JFactory::getDbo();
+			$query = $db->getQuery(true);
+			$query->select('id, alias, catid')
+				->from('#__content')
+				->where('id = ' . $tosarticle);
+			$db->setQuery($query);
+			$article = $db->loadObject();
+			$slug    = $article->alias ? ($article->id . ':' . $article->alias) : $article->id;
+			$url     = ContentHelperRoute::getArticleRoute($slug, $article->catid);
```
Comment (zero-24) [inline plugins/user/profile/fields/tos.php]: @joomdonation @Hackwar I'm not 100% sure. Can we realy use the `$slug` here?

If we follow the doc comment here:
https://github.com/joomla/joomla-cms/blob/staging/components/com_content/helpers/route.php#L26

The first value needs to be a integer that is the article ID or I'm wrong?

File: plugins/user/profile/fields/tos.php (hunk 1 above)
Comment (joomdonation) [inline plugins/user/profile/fields/tos.php]: Yes. That line of code is not used at all. In that block of code, if the article is not selected, it will go to the else block:
```
$link = $text;
```
Infact, when no article is selected, this tos field will be removed from the form https://github.com/joomla/joomla-cms/blob/staging/plugins/user/profile/profile.php#L265

So the code is correct.

File: plugins/user/profile/fields/tos.php (hunk 2 above)
Comment (joomdonation) [inline plugins/user/profile/fields/tos.php]: Yes. It was suggested by Hannes. And I see that it is using in Joomla core as well, so I know it is correct (although I don't know the reason behind this). Sample:

Slug is calculated here https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/category/view.html.php#L84

And then used here https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/category/tmpl/default_articles.php#L128

Comment (Hackwar) [inline plugins/user/profile/fields/tos.php]: Yes, this needs to be the slug. The router does not look up the slug for the article. It does so for the category.

Comment (joomdonation) [inline plugins/user/profile/fields/tos.php]: Hmm. Seems passing ID will be OK as well because if the router does not see the alias, it will query the database to build the slug in the router: https://github.com/joomla/joomla-cms/blob/staging/components/com_content/router.php#L104

A question for Hannes (not related to this PR). Base on your feedback, it seems catId is needed for article router ? If it is correct, then should we get catid based on article ID if catid is not passed to getArticleRoute method here https://github.com/joomla/joomla-cms/blob/staging/components/com_content/helpers/route.php#L34 ?

Comment (Hackwar) [inline plugins/user/profile/fields/tos.php]: No, passing just the ID is NOT okay as well, because then you will have 2 different URLs to the same content, once with and once without slug. And no, I don't want to retrieve the catid in ContentHelperRoute, because that would dramatically increase the number of queries per page. There might be sites out there where this leads to hundreds of extra queries. We actually should remove that the catid parameter is optional, but that is a break in backwards compatibility and thus not possible. Since we are dropping ContentHelperRoute mostly anyway in 3.5, I strongly suggest to not change anything there.

Comment (joomdonation) [inline plugins/user/profile/fields/tos.php]: OK. Thanks Hannes for the explanation. Then we will just need someone to get this PR merged to fix the issue.

**Comment by designbengel** [comment]
Tested successfully with SEF on and with URL rewriting on.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5968">issues.joomla.org/joomla-cms/5968</a>.</sub>

**Comment by zero-24** [comment]
RTC based on the lastes tests Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5968">issues.joomla.org/joomla-cms/5968</a>.</sub>
