### PR TITLE
[5.4] Fix crash in Calendar field with invalid date format

### LINKED ISSUE #46708: Call to a member function format() on false on calendar custom field with wrong date format
### Steps to reproduce the issue
- create a custom field type calendar for all categories
- create an article
- enter a wrong formated date like 01.01.20261 in the custom field
- save

### Expected result
i expect a joomla warning that the article can`t be saved with a wrong formated date field

### Actual result
PHP Error Message 
Call to a member function format() on false

### System information (as much as possible)
- Joomla! 6.0.2 Stable
- PHP Version: 8.4.16-nmm1
- Database: 10.6.22-MariaDB
- Server OS: 22.04.1-Ubuntu
- Webserver: Apache

### Additional comments
Screenrecord

Image

### PR DESCRIPTION
**Pull request by krishnagandhicode**
Pull Request fixes #46708 

### Summary of Changes
This PR fixes a fatal error (`Call to a member function format() on bool`) that occurs when a Calendar field receives an invalid date format.

Previously, `CalendarField::filter()` did not check if `DateTime::createFromFormat()` failed (returned `false`), leading to a crash when calling `->format()` when the result is boolean.

### Testing Instructions
1. Create a Custom Field of type "Calendar"
2. Create or Edit an Article
3. In the Calendar field, manually type an invalid date. Use a format that breaks your specific language settings - for eg:
   * **For English (Y-m-d):** Type `202655-02-04`
   * **For French/German (d-m-Y):** Type `01-01-200566`
4. save.

### Actual result BEFORE applying this Pull Request
The site crashes with `0 Call to a member function format() on bool`.

### Expected result AFTER applying this Pull Request
The site displays a Error Page (Exception) with a clear message identifying the specific field:
"An error has occurred. 0 Invalid field: Start Publishing" (or the **label of the specific field being tested**, e.g: "Invalid field: Created Date").

The save is blocked, and the page reloads gracefully.

A specific error message appears identifying the broken field: "Invalid field: Start Publishing" (or the label of your custom field).

**Note:** I am relatively new to contributing to the core codebase, I am very open to feedback, If there is a preferred way to handle the translation keys or validation logic, I would appreciate your guidance!

### Link to documentations
Please select:
- [ ] Documentation link for guide.joomla.org: <link>
- [x] No documentation changes for guide.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by krishnagandhicode** [comment]
> @krishnagandhicode Please fix the code style errors reported here: https://github.com/joomla/joomla-cms/actions/runs/21680625878/job/62514601493?pr=46833
> 
> First of all use spaces and not tabs for indentation.

Thanks, on it : )

File: libraries/src/Form/Field/CalendarField.php [hunk 1]
```diff
@@ -402,7 +402,13 @@ public function filter($value, $group = null, ?Registry $input = null)
         }
 
         if ($this->filterFormat) {
-            $value = \DateTime::createFromFormat($this->filterFormat, $value)->format('Y-m-d H:i:s');
+            $date = \DateTime::createFromFormat($this->filterFormat, $value);
+            if ($date === false) {
+                // Result: "Invalid form: Date"
+                Factory::getApplication()->enqueueMessage(Text::_('JGLOBAL_VALIDATION_FORM_FAILED') . ': ' . Text::_('JDATE'), 'warning');
```
Comment (Fedik) [inline libraries/src/Form/Field/CalendarField.php]: It should throw an exception, should crash.
But with better message.

Comment (krishnagandhicode) [reply libraries/src/Form/Field/CalendarField.php]: Thanks @Fedik 

my first thought was actually to use an Exception just like you said. But then I realized it redirects the user to  the generic error page , forcing them out of the editor and putting unsaved content at risk.

that is why I used enqueueMessage -  it keeps the user safely on  the page.

Also, if this field is critical, the user can simply mark it as "Required" in the field settings. Since my fix returns an empty value for invalid dates, the standard Joomla form validation will automatically catch it and stop the save (without a crash).

just curious(to learn) is this approach acceptable, or do you we prefer the strict Exception?

Comment (brianteeman) [reply libraries/src/Form/Field/CalendarField.php]: This is the wrong error message. 

Image

It should be invalid field not invalid form

Perhaps this is the correct string JLIB_FORM_VALIDATE_FIELD_INVALID

Comment (krishnagandhicode) [reply libraries/src/Form/Field/CalendarField.php]: Thanks @brianteeman, I have updated the code to use JLIB_FORM_VALIDATE_FIELD_INVALID , the error message is now:
Screenshot 2026-02-05 013506

Comment (exlemor) [reply libraries/src/Form/Field/CalendarField.php]: I have tested and it does behave as shown above... but I don't know if that's a good thing or if this currently how it is done or not but it seems illogical to save Article if the field is wrong no?

I could totally see someone type in the wrong date (not pay attention), press Save + Close and then get those messages and move on (as in quickly/because they have something else to do elsewhere in the site) not realizing that the date didn't actually get saved...

Comment (Fedik) [reply libraries/src/Form/Field/CalendarField.php]: > But then I realized it redirects the user to the generic error page

It do not really redirect but just an error page, you still can click browser back button and re-edit.

In any case it should throw an exception if the value cannot be processed correctly.

Comment (krishnagandhicode) [reply libraries/src/Form/Field/CalendarField.php]: @Fedik Understood.

I have updated the PR to throw an Exception.

the error message now uses JLIB_FORM_VALIDATE_FIELD_INVALID ("Invalid field: Date") as mentioned by @brianteeman

@exlemor Thanks for the feedback!, this fix resolves your concern about invalid data being saved silently - the system will now stop the process entirely.

Comment (joomdonation) [reply libraries/src/Form/Field/CalendarField.php]: > In any case it should throw an exception if the value cannot be processed correctly.

@Fedik @krishnagandhicode  We should not throw an unrecoverable Exception (basically, make the page crash) because of wrong entered data. Better show error message and allow users to correct the data. Maybe in case data could not be filtered, we can return it as how it is. But we should add `validate="Calendar"` to the field to allow [CalendarRule ](https://github.com/joomla/joomla-cms/blob/5.4-dev/libraries/src/Form/Rule/CalendarRule.php) to validate and return error to users. But I'm unsure if `CalendarRule` is properly implemented because it seems it does not care about date format of the field, always return true if a Date object can be created from the passed value https://github.com/joomla/joomla-cms/blob/5.4-dev/libraries/src/Form/Rule/CalendarRule.php#L58

Comment (Fedik) [reply libraries/src/Form/Field/CalendarField.php]: The code should crash, or else it will be impossible to catch the error in future.

Comment (Fedik) [reply libraries/src/Form/Field/CalendarField.php]: Filtering happens before validation, so the wrong value will not reach CalendarRule.

Comment (joomdonation) [reply libraries/src/Form/Field/CalendarField.php]: > Filtering happens before validation, so the wrong value will not reach CalendarRule.

Only if we throw Exception. If we do not throw Exception, validation can validate the wrong entered value and display error. It is better (and right behavior) than making it crash

Comment (Fedik) [reply libraries/src/Form/Field/CalendarField.php]: That can work, but it is extra unneeded complication. 
Just crash the code but with better message. There is no b/c break as it already crashes.

Manual date typing is buggy anyway and should be blocked at some point.

**Comment by krishnagandhicode** [comment]
> I cannot reproduce the issue. On "**Start publishing**" field I type 05-02-2026 (d-m-Y). When I click save, the article is saved without errors, but the date is changed to 2010-08-19 00:00:00
> 
> P.S. I did not create a custom field (as suggested by Brian).

@mariantanase Thanks for testing.

To reproduce the Fatal Error (Crash), please try this:- Enter: 202655-02-04  (Year 202655)


That should trigger the fatal exception we are trying to fix.

File: libraries/src/Form/Field/CalendarField.php [hunk 2]
```diff
@@ -402,7 +402,12 @@ public function filter($value, $group = null, ?Registry $input = null)
         }
 
         if ($this->filterFormat) {
-            $value = \DateTime::createFromFormat($this->filterFormat, $value)->format('Y-m-d H:i:s');
+            $date = \DateTime::createFromFormat($this->filterFormat, $value);
+            if ($date === false) {
+                // Result: Exception page that shows: "Invalid field: Date"
+                throw new \Exception(Text::sprintf('JLIB_FORM_VALIDATE_FIELD_INVALID', Text::_('JDATE')));
```
Comment (Fedik) [inline libraries/src/Form/Field/CalendarField.php]: Please use `$field->title` (which is a text for the field label) instead of `Text::_('JDATE')`. 
Then error will contain the field label.

Comment (krishnagandhicode) [reply libraries/src/Form/Field/CalendarField.php]: Thanks, @Fedik.
I have updated the code to use $this->title, which correctly displays the field label (e.g. "Start Publishing").

Comment (Fedik) [reply libraries/src/Form/Field/CalendarField.php]: Thanks

**Comment by richard67** [comment]
@mariantanase So your test result looks like a successful test to me. If you agree, please go to this PR in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/46833 and use the blue "Test this" button at the top left corner to submit your test result. Thanks in advance, and thanks for testing.
