### PR TITLE
[4.0] Namespace JHtml

### LINKED ISSUE #28249: [4.0] Namespacing Work
### Steps to reproduce the issue
We currently have two parts left of non-namespaced code:

1. "New" MVC (in libraries/joomla)
2. JHtml (in libraries/cms)

#### JHtml
Currently this is not planned to be namespaced. We have introduced a registry system for j4 however the judgement has been made (to date) that moving core to use it would break components doing overrides of core jhtml methods (i.e. with how the `register` command works which would need to go via the HTMLRegistry rather than in JHtml itself. (in j5 we would move https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/HTML/Registry.php the `coreServiceMap` property here into the `serviceMap` property).

#### "New" MVC
As this is used by things such as patchtester and JED it was considered too large a b/c break to immediately remove this in j4 and thus it was scheduled for removal in j5. There are also a small number of other 3rd party components we believe who might also use it and who with the current j5 deprecation would have a small amount of time to migrate back to the MVC layer.

It is possible in j4 we *might* move to a new model layer - which I prototyped in a previous GSOC (see https://github.com/joomla-framework/entities). This would only be if demand for it was required based on how people implement APIs and need things like relations and lazy loading of properties. However if done that would risk 3 MVC layers in core until j5.

### Expected result
Informed Decisions to be made about whether to namespace. Keep unnamespaced. Whether we should merge the libraries/joomla and libraries/cms folders together.

I'm aware a lot of people have strong opinions on some of these b/c issues. So please keep things civil and don't fight each other otherwise I'll just lock this as a heated conversation and let production make the decision without community input.

### PR DESCRIPTION
**Pull request by wilsonge**
This namespaces the JHtml helpers as agreed by Production. Fixes #28249

- Also fixes a bug in the `error_login.php` file of atum that I discovered whilst doing this where we could double register a html service

### Summary of Changes
Namespaces JHtml classes. Note the two classes that are new for J4 (workflowstages and draggable do not have namespace mappings created as they are new for j4)

### Testing Instructions
Ensure CMS works as before in a variety of frontend and backend views

If you are technical review class names make sense - as they aren’t tied to the name being called they can be made longer without any affect

### Documentation Changes Required
Yes. If you are overriding JHtml methods you can no longer use `\Joomla\CMS\HTML\HTMLHelper::register()` you now must instead use

`\Joomla\CMS\HTML\HTMLHelper::getServiceRegistry()->register('jquery', 'MyCustomClass', true);`

The last parameter `$replace` is the important part :) Note that this means you can only override the entire Helper. You can't overload a specific function after this change. In the two cases where people regularly do this in the ecosystem (bootstrap and jquery) this isn't really an issue:
- In JQuery there are only two methods - the second a helper for ajax and it's a minor thing to have to duplicate and I don't see any real issues forthcoming as jQuery is now fairly static
- In Bootstrap whilst there are lots of methods they output html specific to the bootstrap version so you'd need to have overridden them anyhow

### CODE REVIEW

**Comment by richard67** [comment]
@wilsonge PHPCS

File: administrator/templates/atum/error_login.php [hunk 1]
```diff
@@ -61,7 +61,14 @@
 
 $monochrome = (bool) $this->params->get('monochrome');
 
-HTMLHelper::getServiceRegistry()->register('atum', 'JHtmlAtum');
+$htmlHelperRegistry = HTMLHelper::getServiceRegistry();
+
+// We may have registered this trying to load the main login page - so check before registering again
+if (!$htmlHelperRegistry->hasService('atum'))
+{
+	$htmlHelperRegistry->register('atum', 'JHtmlAtum');
```
Comment (C-Lodder) [inline administrator/templates/atum/error_login.php:69]: Should `hasService()` not just be called in the `register()` method? Saves having to manually do it each time.

Comment (wilsonge) [reply administrator/templates/atum/error_login.php:69]: No because you call the same method to override a service like we had to used to do (but with an additional 3rd parameter `true`). This stops extensions overriding each other by accident using the same name

**Comment by wilsonge** [comment]
Tagged as beta blocker

**Comment by richard67** [comment]
@wilsonge Label has been removed after you added it.

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on ed8e2b1e1cf1de9f9f38168cc6b49c2deef33947<br /><br />Tested frontend and backend. No issues found. Did not have overrides in place.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28581">issues.joomla.org/tracker/joomla-cms/28581</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ed8e2b1e1cf1de9f9f38168cc6b49c2deef33947<br /><br />Also tested frontend and backend without having any overrides in place.
I hope I haven't forgotten anything.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28581">issues.joomla.org/tracker/joomla-cms/28581</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28581">issues.joomla.org/tracker/joomla-cms/28581</a>.</sub>

**Review by HLeithner — APPROVED** [review]
The only one is the ListHelper that looks strange but isn't too bad. The rest looks good (code review)

**Comment by wilsonge** [comment]
Ok merging as a first pass. Agree with ListHelper but willing to take followups if anyone comes up with something better
