### PR TITLE
[5.3] Fix missing copyright in media assets

### LINKED ISSUE #46140: Missing Copyright
Something is wrong in our build scripts as it is stripping the copyright and version number from some of our css files.

If you compare bootstrap.min.css in a local checkout with a downloaded package you will see the problem.

This is a serious problem as it puts us in breach of the licence

Image

Thats just an example the same is true for many files. This was first reported in the comments of #45674

### PR DESCRIPTION
**Pull request by LadySolveig**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/46140 .

### Summary of Changes
This pull request refactors how CSS asset versioning is handled in the build process and the handling of license comments in CSS/SCSS files. 
The CLI option has been removed, and the related workflow is now part of the main asset build process.

**Build process and command updates:**

* Removed the previous standalone  `cssversioning` build step and integrate the URL versioning directly into the CSS and SCSS build pipelines, as well as the vendor CSS versioning into the main asset copy and prepare workflows.
* Removes the double execution of the transform function, which led to missing copyright information in css files in the build process.
* Refactored the previous cssversioning for adding of the UTF-8 encoding in vendor css files and also check for copyright comments that are not in the right format to be preserved automatically.

**CLI cleanup:**

* Remove the CSS versioning  CLI option.

**Build process update:**

* Updated the PHP build script to use `npm ci` instead of `npm install --unsafe-perm` .

> [!NOTE]  
> The main goal of this PR is to be able to deliver the missing copyright headers again.
Even though this PR already contains steps to ensure that the assets from the development environment correspond as closely as possible to the final build files, this PR does not yet cover everything. 
The` joomla.asset.json`  files and javascript files are not affected by this PR.

### Testing Instructions

Run `npm ci`

* check that  the copyright information in the media files are handled correctly and not missing 
  -  `media/vendor/bootstrap/css/bootstrap.css`
  - `media/vendor/bootstrap/css/bootstrap.min.css`
  - `media/templates/administrator/atum/css/vendor/fontawesome-free/fontawesome.css`
  - `media/templates/administrator/atum/css/vendor/fontawesome-free/fontawesome.min.css`

**Step 2:**

* check the media files also in the package, that is build from this PR
   -  `media/vendor/bootstrap/css/bootstrap.css`
  - `media/vendor/bootstrap/css/bootstrap.min.css`
  - `media/templates/administrator/atum/css/vendor/fontawesome-free/fontawesome.css`
  - `media/templates/administrator/atum/css/vendor/fontawesome-free/fontawesome.min.css`
  
**Step 3:**
  * check that `@charset "UTF-8";` is on top of each css file and at the beginning of the min.css files

**Step 4:**
* check that the site (installed from the package of this PR ) is working as expected and no media files are missing.

**Step 5: (Advanced)**
* checkout this PR
* run `php ./build/build.php --remote=HEAD`
* remove the media folder and run `npm ci`
* compare the media files from the build package with the files in the media folder previously generated
   (use git or a tool like this https://meldmerge.org/)

### Actual result BEFORE applying this Pull Request

Copyright information in css files missing.

### Expected result AFTER applying this Pull Request

Copyright information in the beginning of the file.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
_I'm offline now for 48 hours_

When testing you should ensure that the contents of the media folder are identical locally and in the download package

**Comment by LadySolveig** [comment]
Good idea for testing :), I've now run it a few times in a row. Everything is working fine for me. I hope someone else will test it too, of course.

**Comment by Fedik** [comment]
> The ordering seems to differ also between different runs of npm ci

Hm, then need to look each particular case. Example, for codemirror the script generate new elements while build, the order may depend from "node modules" lookup script.

But yes, not for this PR.

**Comment by richard67** [comment]
> I have tested this item 🔴 unsuccessfully on [8b064e6](https://github.com/joomla/joomla-cms/commit/8b064e6fc93fdcc73e25a5bf2ceb333199d371a8)

@brianteeman Could you report back what has failed for you? Was it something from [my findings](https://github.com/joomla/joomla-cms/pull/46146#issuecomment-3327194914)? Or was the copyright comment missing somewhere, and I have missed that in my findings?

**Comment by richard67** [comment]
@dgrammatiko What do you think about [my findings above](https://github.com/joomla/joomla-cms/pull/46146#issuecomment-3327194914)? Can we live with that?

**Comment by LadySolveig** [comment]
> ### Comparison of full installation ZIP packages built with and without PR
> 
> Here all differences appear which are mentioned in the previous section and in the next section.
> 
> In addition, there are lots of differences in unminified CSS files which without the PR were modified e.g. by the linter, and now with the PR they are just taken as they are.
> 
> That also means that with the PR applied, these files don't get the `@charset "UTF-8";` at the top.
> 
> This would make sense for vendor files which we don't want to modify.
> 
> But it is also the case for our files.

If I understand correctly, the long-term goal is to have a mostly comparable result in the media files for dev and for the build packages.

But then it is actually the case that, especially with the original CSS files, it makes the most sense to pay attention to the correct format directly and, for example, to have the `@charset ‘UTF-8’;` at the top directly in the file.

SCSS files always have to be compiled, so it's absolutely no problem to process such steps, and the compiled files don't go back into the Git repository after calling `npm ci`.

But any changes made by the linter to the CSS files will always remain different between build and dev files.
Worse still, it would be marked as a changed file every time in the developer branch if you would combine that with `npm ci. 
So ultimately, we have to live with either 
- copying the files 1:1 (then they are comparable) 
- or accepting that they are different in the build package.

Of course, it would be best if they were optimised before being added to the repository.
That's what we do with the php files, after all.

**Comment by LadySolveig** [comment]
> With the other PR #46147 that would be the same for both cases, always version properties added.
> 
> Assuming that we want to use local branches for testing, and it makes sense to test what end users will see, I currently would prefer the other PR, which besides that point has the same results as this one here.

The longer I think about this one, the more I think we should perhaps test it in 6.1, if we really want to, as we will have more time until the productive build and it will probably be called up and tested more frequently.

**Comment by LadySolveig** [comment]
grafik

The code style check runs in the build folder and has nothing to do with what is compiled by the `npm ci` call or the build script.
The code style check runs on the raw source files and not the compiled ones.

File: build/build-modules-js/stylesheets/handle-css.mjs [hunk 1]
```diff
@@ -1,7 +1,8 @@
 import { dirname, sep } from 'node:path';
 
 import pkg from 'fs-extra';
-import { transform as transformCss } from 'lightningcss';
+import { transform as transformCss, composeVisitors } from 'lightningcss';
+import { urlVersioning } from './css-versioning.mjs';
 
 const {
   copy, readFile, writeFile, ensureDir,
```
Comment (richard67) [inline build/build-modules-js/stylesheets/handle-css.mjs]:
```suggestion
  readFile, writeFile, ensureDir,
```
Make linter happy (1 of 2).

File: build/build-modules-js/stylesheets/handle-css.mjs [hunk 2]
```diff
@@ -10,22 +11,43 @@ const {
...
     await ensureDir(dirname(outputFile), { recursive: true, mode: 0o755 });
 
+    let content = await readFile(file, { encoding: 'utf8' });
+
+    // To preserve the licence the comment needs to start at the beginning of the file
+    content = content.startsWith('@charset "UTF-8";\n') ? content.replace('@charset "UTF-8";\n', '') : content;
+
     if (file !== outputFile) {
-      await copy(file, outputFile, { preserveTimestamps: true, overwrite: true });
+
```
Comment (richard67) [inline build/build-modules-js/stylesheets/handle-css.mjs]:
```suggestion
```
Make linter happy (2 of 2).

**Comment by brianteeman** [comment]
> > There is no reason ever for the output of the build script to be different to npm ci EXCEPT for a difference in the version number.
> 
> @brianteeman Then you should support this PR because it reduces these differences. Without this PR e.g. the "media/com_installer/css/installer.css" differs between the result of composer install and npm ci on a local branch, with this PR both are the same. Same for other files.

No I should do what I believe not what you decide I should believe

File: build/build-modules-js/stylesheets/handle-css.mjs (hunk 2 above)
Comment (LadySolveig) [reply build/build-modules-js/stylesheets/handle-css.mjs]: Thank you 💚

**Comment by brianteeman** [comment]
There was no need for that comment

**Comment by muhme** [comment]
I have tested this item :white_check_mark: successfully on fb5ccaa69024b3621ad7bff1b41b911062ecaff1<br /><br />Retested with the following commands, which were noted down to document how the tests were performed and to provide the opportunity to repeat or continue the tests.
```
    git clone https://github.com/joomla/joomla-cms 53
    cd 53
    gh pr checkout 46146
    git tag test-46146 -m test-46146
    composer i
    npm ci
    cp -pr media /tmp/media_first
    php build/build.php --exclude-gzip --exclude-zstd --remote=test-46146
    unzip build/tmp/packages/Joomla_5.3.4-rc2-dev-Development-Full_Package.zip "media/*" -d /tmp
    mv /tmp/media /tmp/media_package
```
* ✅ Test 1 Check copyright information in the media files
  - `media/vendor/bootstrap/css/bootstrap.css`
  - `media/vendor/bootstrap/css/bootstrap.min.css`
  - `media/templates/administrator/atum/css/vendor/fontawesome-free/fontawesome.css`
  - `media/templates/administrator/atum/css/vendor/fontawesome-free/fontawesome.min.css`
* ✅ Test 2 Check the media files also in the package, that is build from this PR
  * Simple compared all 217 `.css` files, they are not only existing, they are are equal:
    ```
    cd /tmp/media_first; find . -name \*.css | while read f; do cmp $f /tmp/media_package/$f; done
    ```
* ✅ Test 3 Check that @charset "UTF-8"; is on top of each css file and at the beginning of the min.css files
  * Checked the 217 files with:
  ```
    find /tmp/media_first -name \*.css | xargs grep -aL '^@charset "UTF-8";' --
    find /tmp/media_package -name \*.css | xargs grep -aL '^@charset "UTF-8";' --
  ```
* ✅ Test 4 Check that the site is working as expected and no media files are missing.
  * Installed manually on localhost from extracted full package
  * Enabled 'Debug System' and 'Log Almost Everything'
  * Created article, viewed and edited on the frontend
  * Uploaded image, cropped and rotated
  * Sended test mail
  * Added Smart Search and tested on frontend
  * Checked Joomla logs, PHP log and HTTP access log for ' 404 '
* ⚠️ Test 5 Compare the media files from build package with `npm ci`
  * As described:
  ```
    rm -rf media /tmp/media_*
    php ./build/build.php --remote=HEAD
    unzip build/tmp/packages/Joomla_5.3.4-rc2-dev-Development-Full_Package.zip "media/*" -d /tmp
    mv /tmp/media /tmp/media_package
    npm ci
    cp -r media /tmp/media_npm
  ```
  * `/tmp/media_first` contains 1'661 files, `/tmp/media_package` contains 2'101 files
    * Difference are additional `.gz` files in package, deleted with:
    `diff -r /tmp/media_npm /tmp/media_package |grep 'Only in ' | sed -e 's/Only in //' -e 's|: |/|' | xargs rm`
  * Remaining differences are checked with `diff -r /tmp/media_npm /tmp/media_package|more`:
    * 36 files differ as seen with `diff -rq /tmp/media_npm /tmp/media_package | wc -l`
    * All 36 files are `*.joomla.asset.json`
    * Only one file (`vendor/joomla.asset.json`) is equal in size
      ```
      diff -rq . ../media_npm | sed -e 's|Files ./||' -e 's/ and .*//' | while read f ; do [ $(wc -c < $f) -ne $(wc -c < ../media_npm/$f) ] || echo "$f equal" ; done
      ```
    * Differences are attached as 
    ```
      diff -r /tmp/media_npm /tmp/media_package > /tmp/diff.txt
    ```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/46146">issues.joomla.org/tracker/joomla-cms/46146</a>.</sub>

**Comment by richard67** [comment]
@muhme The difference in size of the joomla.asset.json files when comparing the npm ci result with the package comes from the version properties for assets being added only for the package. That is ok from my point of view.

**Comment by Fedik** [comment]
One more thing about versioning hash. In theory it possible to update WebAssetmanager to read the main version from json and append to children assets if their version not exists. Then in build we can update only main version in the json.

I have this idea for few years, but to lazy to implement it :smile: 


> The PR does not only fix the copyright issue and duplicate UTF-8 thing issue.

Yes, you are right. I think most critical was copyright.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/46146">issues.joomla.org/tracker/joomla-cms/46146</a>.</sub>

**Comment by HLeithner** [comment]
I have tested this item :white_check_mark: successfully on fb5ccaa69024b3621ad7bff1b41b911062ecaff1<br /><br />I checked about 40 files by hand and all of them have now the correct copyright header and Utf8 statement. Json ordering and different css order after compression is a bit annoying... but that's for another pr.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/46146">issues.joomla.org/tracker/joomla-cms/46146</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you all very much for your fantastic support and cooperation. I am very grateful to you for the extensive testing!
