### PR TITLE
[6.0] Fix PHP warnings when opening Page Break modal

### LINKED ISSUE #46901: [6.0] Page Break
### Steps to reproduce the issue
Set php error reporting to maximum
In Joomla 6.0+ open an article for editing and try to insert a page break using the xtd-editor button

### Expected result
Modal opens for you to enter the title etc without error

### Actual result
```

Warning
: Attempt to read property "id" on null in
D:\repos\j6\administrator\components\com_content\src\View\Article\HtmlView.php
on line
139
```

```
Warning
: Attempt to read property "checked_out" on null in
D:\repos\j6\administrator\components\com_content\src\View\Article\HtmlView.php
on line
140

```

Image

### System information (as much as possible)
Confirmed working in 5.x
Not working in 6.0-dev or 6.1-dev
php 8.4.18

### Additional comments
Last change to this file was made https://github.com/joomla/joomla-cms/pull/45913

### PR DESCRIPTION
**Pull request by sathwikre**
Fixes PHP warnings caused by accessing properties on a null article item
when opening the Page Break modal in Joomla 6.

The Page Break modal can be opened without a loaded article item, which
caused warnings for id and checked_out in the article HtmlView.

Fixes #46901

### CODE REVIEW

**Comment by mariantanase** [comment]
I have tested this item :white_check_mark: successfully on 69a0e27bea91889a079d136c22edf21886dd3c97<br /><br />Confirmed the fix for Joomla 6.1.0 beta 1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/46908">issues.joomla.org/tracker/joomla-cms/46908</a>.</sub>

**Comment by richard67** [comment]
@sathwikre As the fixed issue is specific for 6.x and does not happen in 5.4, I've allowed myself to rebase your PR to 6.1-dev and fix the conflict caused by changes made in the 6.0-dev branch in past at the same place. Please check if the changed file on GitHub shows what you expect.

@mariantanase Please test again, preferably on 6.0 and not 6.1, and submit the test result again. Thanks in advance.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/46908">issues.joomla.org/tracker/joomla-cms/46908</a>.</sub>

**Comment by joomdonation** [comment]
> @joomdonation Please confirm or correct me.

Yes, that's correct. As of right now, the PR contains unnecessary changes and these changes should be reverted. The only changes needed to solve the issue is https://github.com/joomla/joomla-cms/pull/46908#issuecomment-3945363970 . @sathwikre Could you please check ?

**Comment by sathwikre** [comment]
Thanks for the clarification 👍
I’ve reverted all unrelated changes and kept only the early return in addToolbar() for the pagebreak layout.
Please let me know if this looks correct now.

File: administrator/components/com_content/src/View/Article/HtmlView.php [hunk 1]
```diff
@@ -77,10 +77,6 @@ public function __construct(array $config)
      */
     protected function initializeView()
     {
-        if ($this->getLayout() == 'pagebreak') {
-            return;
-        }
-
```
Comment (richard67) [inline administrator/components/com_content/src/View/Article/HtmlView.php:83]: Why do you remove this?

**Comment by sathwikre** [comment]
Sorry for the confusion — that was my mistake.
I initially removed that check while trying to simplify the flow, but I understand now that it is still required in initializeView() and should not have been touched.
I’ve restored the original code there and kept only the early return in addToolbar() for the pagebreak layout, which is the actual fix needed for this issue.
Thanks for catching this.

**Comment by richard67** [comment]
@mariantanase @OctavianC @basn63 Could you test this PR again with the latest changes? Thanks in advance.
